### PR TITLE
[7.5.x] DROOLS-2371: Unable to complete your request. The following exception occurred: (TypeError) in Guided Decision Table Graph

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-2371

This is the corollary of https://github.com/kiegroup/drools-wb/pull/824 for 7.5.x

(cherry picked from commit 52edf69c27de519d1fff9465f10461d5533f8c06)

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@jomarko We may need the CDI test ```destroy()``` fix on 7.5.x too:
```
java.lang.NullPointerException: null
	at org.jboss.weld.context.AbstractContext.destroyContextualInstance(AbstractContext.java:139)
	at org.jboss.weld.context.AbstractContext.destroy(AbstractContext.java:153)
	at org.jboss.weld.context.AbstractSharedContext.destroy(AbstractSharedContext.java:61)
	at org.jboss.weld.context.AbstractSharedContext.invalidate(AbstractSharedContext.java:56)
	at org.jboss.weld.bootstrap.WeldRuntime.shutdown(WeldRuntime.java:56)
	at org.jboss.weld.bootstrap.WeldBootstrap.shutdown(WeldBootstrap.java:113)
	at org.jboss.weld.environment.se.WeldContainer.shutdown(WeldContainer.java:267)
	at org.jboss.weld.environment.se.Weld.shutdown(Weld.java:633)
	at org.guvnor.test.CDITestSetup.cleanup(CDITestSetup.java:50)
	at org.drools.workbench.screens.enums.backend.server.EnumServiceImplCDITest.tearDown(EnumServiceImplCDITest.java:46)
```

**Comment by jomarko** [comment]
@manstis yes, I had already opened PR kiegroup/appformer#155  for that, however @ederign was not for merging, so I don't know what to do. @ederign would you mind reconsider if we could merge the PR into 7.5.x? It fixes random fails in tests.

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
@jomarko it's not my decision to don't merge the PR, the branch is closed for blockers-only.
Needs @porcelli , @krisv or @etirelli approval.

**Comment by triceo** [comment]
@ederign I think test-only changes are exceptions to that rule. I'm certainly OK with that thing being merged.

**Comment by etirelli** [comment]
@triceo is correct, tests and docs can always be merged. 

also, this ticket is targeted to DM 7.0.1, so this fix needs to go in.

https://issues.jboss.org/browse/RHDM-471

**Comment by jomarko** [comment]
Well, I recreated the PR https://github.com/kiegroup/appformer/pull/232

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
@tsurdilo Test ```BaseElementFeaturesTest.testBaseElementDocumentationFeature()``` has been consistently failing on 7.5.x. Could you please take a look.
```
org.jbpm.designer.bpmn2.util.BaseElementFeaturesTest.testBaseElementDocumentationFeature

Failing for the past 3 builds (Since Unstable#5 )
Took 3 ms.
Error Message
Error getting base element feature: index=0, size=0
Stacktrace
java.lang.AssertionError: Error getting base element feature: index=0, size=0
	at org.junit.Assert.fail(Assert.java:88)
	at org.jbpm.designer.bpmn2.util.BaseElementFeaturesTest.testBaseElementDocumentationFeature(BaseElementFeaturesTest.java:59)
```

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
@tsurdilo Test ```BaseElementFeaturesTest.testBaseElementDocumentationFeature()``` continues to fail consistently on 7.5.x. Could you please take a look.
```
org.jbpm.designer.bpmn2.util.BaseElementFeaturesTest.testBaseElementDocumentationFeature

Failing for the past 3 builds (Since Unstable#5 )
Took 3 ms.
Error Message
Error getting base element feature: index=0, size=0
Stacktrace
java.lang.AssertionError: Error getting base element feature: index=0, size=0
	at org.junit.Assert.fail(Assert.java:88)
	at org.jbpm.designer.bpmn2.util.BaseElementFeaturesTest.testBaseElementDocumentationFeature(BaseElementFeaturesTest.java:59)
```

**Comment by jomarko** [comment]
@manstis The test is failing because PR [2] is not merged. However I am totally not sure why [1] and [2] are not both for the same repository and why test on master pass even without the [1] being merged.
[1]
https://github.com/jboss-integration/jboss-integration-platform-bom/pull/419
[2]
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/712

**Comment by tsurdilo** [comment]
@jomarko @manstis Master branch is fine because of commit - https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/3c5953b6ede178c81638ba63bc23184f56b61ced

7.5.x jbpm-designer test is failing because of https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/712 needs to be merged

@jomarko the test is fine on master even tho jboss-integration/jboss-integration-platform-bom#419 has not be merged because https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/3c5953b6ede178c81638ba63bc23184f56b61ced overwrites this setting. Your [1] is a pr for when the boms align again which at the time of pr was not the case.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
@jomarko Am I waiting for a green full build? Your [comment](https://github.com/kiegroup/drools-wb/pull/827#pullrequestreview-102998691) implies you've done it locally?

**Comment by jomarko** [comment]
@manstis lets try few more times, jenkins execute full downstream build

**Pull request merged**
