### PR TITLE
GUVNOR-3231: Select proper operator in GDT Column wizard

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
Fails are in community selenium tests, if you check the downstream build, now the **-please choose-** placeholder is selected correctly by default, not the **equal to**.

**Comment by karreiro** [comment]
Jenkins execute full downstream build

**Comment by karreiro** [comment]
Jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Pull request merged**
