### PR TITLE
DROOLS-4433 : Add the ability to move constraints within patterns in the same way we can move patterns within rules to Guided Rules and Guided Rule Templates

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-4433

https://github.com/kiegroup/drools/pull/2502
https://github.com/kiegroup/drools-wb/pull/1215

### CODE REVIEW

**Comment by Rikkola** [comment]
@manstis @jomarko If you two could please review.

**Comment by jomarko** [comment]
No comments to code.

**Comment by jomarko** [comment]
### Manual Review Note 1
We are either offering the Move Up/Down for inappropriate blocks or there is an issue. see the video https://issues.jboss.org/secure/attachment/12454339/move-up.webm

Trying to move up **the following exists** doesn't work. Used sample **Mortgages** project, **Bankruptcy history.rdrl**

**Comment by jomarko** [comment]
No other issues found during manual review.

**Comment by Rikkola** [comment]
@kiegroup/gatekeepers Could I get a merge please.

**Pull request merged**
