### PR TITLE
[DROOLS-4060] CSS bug in Test Scenario setting panel when namespace is long

### PR DESCRIPTION
**Pull request by yesamer**
@kkufova @gitgabrio @danielezonca @jomarko Can you please review it?

https://issues.jboss.org/browse/DROOLS-4060

### CODE REVIEW

**Comment by kkufova** [comment]
I agree with @danielezonca, I like this approach a lot, but I would prefer if **all** the properties that **cannot** be edited looked the same (like this).

**Comment by yesamer** [comment]
@danielezonca @kkufova Done, can you please check it?

**Comment by yesamer** [comment]
@manstis  Can you please merge it on master?

**Comment by yesamer** [comment]
@manstis Can you please merge it on master?

**Pull request merged**
