### PR TITLE
[7.3.x] GUVNOR-3508: test offered operators by rule editor widget

### PR DESCRIPTION
**Pull request by jomarko**
This is cherry-pick of #627 

There were some import conflicts, lets wait for jenkins saying I resolved them correctly or not.

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins please retest this 
I believe you will result with green this time

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by Rikkola** [comment]
Heh. @jomarko Didn't help that you believed in him :-)

**Comment by jomarko** [comment]
You are right Toni, new day is new chance,
jenkins please retest this

**Comment by manstis** [comment]
Jenkins please be a dear and retest this one more time.

**Comment by jomarko** [comment]
Dear jenkins, I think you could tell me that there is one missing piece of puzzle. https://github.com/kiegroup/kie-wb-common/pull/1183
jenkins please retest this

**Comment by jomarko** [comment]
thank you jenkins

**Pull request merged**
