### PR TITLE
removed dependency to kie-platform-bom

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
all related PRs ..:

https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/982
https://github.com/kiegroup/kie-soup/pull/102
https://github.com/kiegroup/appformer/pull/737
https://github.com/kiegroup/droolsjbpm-knowledge/pull/392
https://github.com/kiegroup/drools/pull/2446
https://github.com/kiegroup/optaplanner/pull/521
https://github.com/kiegroup/jbpm/pull/1513
https://github.com/kiegroup/kie-jpmml-integration/pull/8
https://github.com/kiegroup/droolsjbpm-integration/pull/1863
https://github.com/kiegroup/droolsjbpm-tools/pull/96
https://github.com/kiegroup/kie-uberfire-extensions/pull/86
https://github.com/kiegroup/kie-wb-playground/pull/77
https://github.com/kiegroup/kie-wb-common/pull/2744
https://github.com/kiegroup/drools-wb/pull/1189
https://github.com/kiegroup/optaplanner-wb/pull/341
https://github.com/kiegroup/jbpm-designer/pull/855
https://github.com/kiegroup/jbpm-work-items/pull/107/files
https://github.com/kiegroup/jbpm-wb/pull/1367
https://github.com/kiegroup/kie-wb-distributions/pull/945
https://github.com/kiegroup/optaweb-employee-rostering/pull/258

**Comment by gitgabrio** [comment]
@mbiarnes @manstis @danielezonca @yesamer 

Please follow that:
_drools-wb_ "extends" kie-parent

`<parent>
    <groupId>org.kie</groupId>
    <artifactId>kie-parent</artifactId>
  </parent>`

and uses a series of bom to "compose " dependency management.

both _kie-soup-bom_ and _uberfier-bom_ extend the same _kie-parent_, while the others extend _kie-user-bom-parent_ that, in turns, extend  _jboss-parent_.
To complete the picture, _jboss-parent_ is also the parent of _kie-parent_.

I guess it is the same for all other PRs/projects. 
The overall design does not seem really clean and I fear it may raise potential issues: on one side we are saying that _drools-wb_ is a "son" of _kie-parent_, and on the other side we are further "extending" it with other "twins" that - in turns - may potentially override something of the same parent. 
This issue is not related specifically to this PR, but I did not realized it before, and I think this is a good place to just pointing out.
/---/
I can not verify these bunch of PRs because to be sure I should delete my local repo' folders and install all those PRs offline. 
If it works, fine for me.

**Comment by mbiarnes** [comment]
> @mbiarnes @manstis @danielezonca @yesamer
> 
> Please follow that:
> _drools-wb_ "extends" kie-parent
> 
> `<parent> <groupId>org.kie</groupId> <artifactId>kie-parent</artifactId> </parent>`
> 
> and uses a series of bom to "compose " dependency management.
> 
> both _kie-soup-bom_ and _uberfier-bom_ extend the same _kie-parent_, while the others extend _kie-user-bom-parent_ that, in turns, extend _jboss-parent_.
> To complete the picture, _jboss-parent_ is also the parent of _kie-parent_.
> 
> I guess it is the same for all other PRs/projects.
> The overall design does not seem really clean and I fear it may raise potential issues: on one side we are saying that _drools-wb_ is a "son" of _kie-parent_, and on the other side we are further "extending" it with other "twins" that - in turns - may potentially override something of the same parent.
> This issue is not related specifically to this PR, but I did not realized it before, and I think this is a good place to just pointing out.
> /---/
> I can not verify these bunch of PRs because to be sure I should delete my local repo' folders and install all those PRs offline.
> If it works, fine for me.

Don't know if I follow you.
https://github.com/mbiarnes/droolsjbpm-build-bootstrap/blob/rem_kie_pf_bom/kie-soup-bom/pom.xml#L24 and https://github.com/mbiarnes/droolsjbpm-build-bootstrap/blob/rem_kie_pf_bom/uberfire-bom/pom.xml#L24 inherit from kie-user-bom-parent (look at the PR of droolsjbpm-build-bootstrap)

**Comment by gitgabrio** [comment]
> Don't know if I follow you.
> https://github.com/mbiarnes/droolsjbpm-build-bootstrap/blob/rem_kie_pf_bom/kie-soup-bom/pom.xml#L24 and https://github.com/mbiarnes/droolsjbpm-build-bootstrap/blob/rem_kie_pf_bom/uberfire-bom/pom.xml#L24 inherit from kie-user-bom-parent (look at the PR of droolsjbpm-build-bootstrap)

@mbiarnes 
First of all - to be clear - I think this has nothing really to do with your PRs. It is *good* that now "imported" boms have a different inheritance line (I missed that).
Somehow  the "design" issue (IMO) is still there at different level - a "diamond" pattern - but we may better analyze it in future

**Pull request merged**
