### PR TITLE
DROOLS-6075: Scenario Simulation type error popup when constraint applied to DMN data type

### PR DESCRIPTION
**Pull request by yesamer**
**JIRA**: https://issues.redhat.com/browse/DROOLS-6075

This PR aim is to provide proper feedback when a DMNType used in TestScenario was changed in DMN Editor in this ways:
- Added constraint to a DMNType;
Screenshot from 2021-03-16 21-35-54
- Remove constraint to a DMNType;
 Screenshot from 2021-03-16 21-33-07
In this case, the user needs to redefine the wrong column (remove and add again or just override it with the same type)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
jenkins run fdb

**Review by jstastny-cz — APPROVED** [review]
LGTM. I've run regression suite, all seems work fine.

**Review by karreiro — APPROVED** [review]
Great stuff, @yesamer! The documentation in the method was really helpful, and the code is quite clean :-)

**Pull request merged**
