### PR TITLE
DROOLS-6268 : Fix for GRE in

### PR DESCRIPTION
**Pull request by Rikkola**
**JIRA**:  

[DROOLS-6268](https://issues.redhat.com/browse/DROOLS-6268)
[war](https://www.dropbox.com/s/uj2gq20cf0d6ilu/business-central-7.53.0-SNAPSHOT-wildfly19.war?dl=0)

**referenced Pull Requests**: 

* https://github.com/kiegroup/kie-soup/pull/193
* https://github.com/kiegroup/drools/pull/3524
* https://github.com/kiegroup/kie-wb-common/pull/3619
* https://github.com/kiegroup/drools-wb/pull/1481

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
@jomarko The most problematic thing with this is testing the changes here.

**Review by jomarko — CHANGES_REQUESTED** [review]
Save and reopen causes the bound variables are parsed as string constants. More details in jira comment.

**Comment by Rikkola** [comment]
@jomarko fixed, new war linked in the description.

**Review by karreiro — APPROVED** [review]
Thank you, @Rikkola!

**Review by jomarko — COMMENTED** [review]
code review inline. I have trouble to test produced rule by legacy or non legacy test scenario, working on it.

**Review by jomarko — APPROVED** [review]
Thank you @Rikkola

**Pull request merged**
