### PR TITLE
BAQE-488: Add test for creating enum which already exists

### PR DESCRIPTION
**Pull request by tomasdavidorg**
https://github.com/kiegroup/jbpm-designer/pull/808
https://github.com/kiegroup/kie-wb-common/pull/2023
https://github.com/kiegroup/drools-wb/pull/908

### CODE REVIEW

**Comment by manstis** [comment]
@jomarko IDK if you need review these too?

**Comment by tomasdavidorg** [comment]
Are we ok to merge this?

**Comment by manstis** [comment]
@tomasdavidorg Yes, sure... you just need to nudge people to do so when they are approved and green (as nobody, other than you and your own PRs, constantly monitors _all_ open PRs to check when they can be merged) :-)

**Comment by tomasdavidorg** [comment]
@manstis Thanks. I wasn't sure who I should ask. :-)

**Pull request merged**
