### PR TITLE
[do not merge] DROOLS-2623: Stabilize xls decision table tests

### PR DESCRIPTION
**Pull request by jomarko**
Unify drools date format initialization to get tests not affecting each other

### CODE REVIEW

**Comment by jomarko** [comment]
@manstis @karreiro @Rikkola anybody interested, please have a look.

**Comment by Rikkola** [comment]
Sounds and looks like a good change. +1

**Comment by jomarko** [comment]
Well jenkins obviously behave differently than local machine, argh. Keeping this open a and will try to investigate.

**Comment by jomarko** [comment]
@manstis will try, as you can see, it fails on jenkins, it is fine on local machine.

**Comment by jomarko** [comment]
Replaced with #1037

**Pull request closed without merging**
