### PR TITLE
[JBPM-7869] NoClassDefFoundError warnings when starting Workbench

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/JBPM-7869

### CODE REVIEW

**Comment by Rikkola** [comment]
@jomarko @elguardian Here is what I propose for a fix.

**Comment by jomarko** [comment]
kie-drools-wb works fine, building kie-wb right now

**Comment by Rikkola** [comment]
@manstis Good afternoon. If you could please merge.

**Comment by manstis** [comment]
@Rikkola when it's green, sure.

**Comment by ederign** [comment]
jenkins retest this

**Pull request merged**
