### PR TITLE
[AF-1528] Servlet ContextListener deployer 

### PR DESCRIPTION
**Pull request by desmax74**
Enabled the Servlet listener to deploy jars during the startup of the webapp

### CODE REVIEW

**Comment by desmax74** [comment]
https://github.com/kiegroup/appformer/pull/450

@porcelli @jhrcek @domhanak

**Comment by porcelli** [comment]
Servlet container automatically picks the `@WebListener` annotation, you don't need declare it in web.xml

**Comment by desmax74** [comment]
@porcelli we are using a web.xml with servlet 2.5

**Comment by porcelli** [comment]
its likely just a left over from an old upgrade, we should just update the servlet reference, but quite sure WF/EAP will pickup based on annotation

**Pull request closed without merging**
