### PR TITLE
GUVNOR-3163: [Guided Decision Table] "Entry point" and "Binding" cannot be updated

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/GUVNOR-3163

Before:
before-

After:
after-

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
@jomarko you can try it manually right now (if you want to). The Jenkins failure is not related to the change, see:
```
11:11:27 Caused by: org.kohsuke.github.HttpException: Server returned HTTP response code: -1, message: 'null' for URL: https://api.github.com/repos/kiegroup/kie-wb-playground
[...]
11:11:27 Caused by: java.net.SocketTimeoutException: Read timed out
```

**Comment by jomarko** [comment]
@karreiro will, do, thanks for notice.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins plase execute full downstream build.

**Pull request merged**
