### PR TITLE
[DROOLS-3688] Implement usage of ScenarioHeaderMetaData.getMetadataType

### PR DESCRIPTION
**Pull request by annabaker**
@gitgabrio @kkufova

### CODE REVIEW

**Comment by annabaker** [comment]
jenkins please retest

**Comment by gitgabrio** [comment]
@kkufova 
Could you take a look at this? Thx!

**Comment by gitgabrio** [comment]
jenkins please retest this

**Comment by gitgabrio** [comment]
@manstis
Hi! Could you please merge this, squashing commits? Thanks!

**Pull request merged**
