### PR TITLE
DROOLS-5792: Error thrown when assigning a multiple nested collection property

### PR DESCRIPTION
**Pull request by yesamer**
Holding variable `nestedFactModelTree ` wasn't used during object path navigation. It was previously used the original factMapping tree, which holds the first level object information.

**JIRA**: https://issues.redhat.com/browse/DROOLS-5792

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by danielzhe — APPROVED** [review]
LGTM! Thank you, @yesamer !

**Comment by jstastny-cz** [comment]
jenkins do fdb

**Comment by yesamer** [comment]
jenkins do fdb

**Review by jstastny-cz — APPROVED** [review]
LGTM, verified in FDB.

**Pull request merged**
