### PR TITLE
[DROOLS-3338] Preventing enter propagation

### PR DESCRIPTION
**Pull request by yesamer**
@kkufova @gitgabrio @danielezonca

see https://issues.jboss.org/browse/DROOLS-3338

### CODE REVIEW

**Comment by kie-ci10** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by danielezonca** [comment]
ok to test

**Comment by gitgabrio** [comment]
Fine for me
@kkufova Pls check in different browsers, at first sight we could not recreate the bug in Firefox.

**Comment by manstis** [comment]
@gitgabrio I told you it'd be due to a HTML FORM! ;-)

**Comment by danielezonca** [comment]
> @gitgabrio I told you it'd be due to a HTML FORM! ;-)

@manstis 

Me too but he is a lazy guy! :-D :-D

**Pull request merged**
