### PR TITLE
[7.3.x] GUVNOR-3471: [Guided Decision Table] Delete Multiple Cells and Rows f…

### PR DESCRIPTION
**Pull request by markcoble**
…rom context menu

@manstis 
https://issues.jboss.org/browse/GUVNOR-3471

### CODE REVIEW

**Comment by manstis** [comment]
@markcoble One more thing... it's nice to put the branch name in the PR title too (e.g. https://github.com/kiegroup/drools/pull/1472). I've updated this PR's title for you.

**Comment by markcoble** [comment]
@manstis thanks.  Has this been merged?  I see it committed to 7.3.x but the PR still shows open.

**Comment by manstis** [comment]
Hi @markcoble this PR isn't merged (as you correctly saw) however nor is it committed to the 7.3.x branch. See [here](https://github.com/kiegroup/drools-wb/commits/7.3.x). When @jomarko approves this PR I'll merge it.

**Comment by jomarko** [comment]
Stay tuned, I am building locally right now.

**Comment by markcoble** [comment]
@manstis i saw your commit for 3491 and read 3471. oops.

**Pull request merged**
