### PR TITLE
[7.5.x] DROOLS-2160: Introduce tabs for KieSessionSelector and AuditLog (#754)

### PR DESCRIPTION
**Pull request by jomarko**
* DROOLS-2160: Introduce tabs for KieSessionSelector and AuditLog

DROOLS-2160: Move config and audit to separate tabs

* DROOLS-2160: Formatting issues and more tests

* DROOLS-2160: refacotring MVP of new pages view

* DROOLS-2160: Use Errai Html templated table for showing audit

* DROOLS-2160: Post Review Action - Improve Templating

This is corollary of #754

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@jomarko Advised this is a cherry-pick.

**Pull request merged**
