### PR TITLE
[7.5.x] DROOLS-2228: [Guided Decision Table] Rename Set the field value with Work Item parameter column

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-2228

This is the corollary of https://github.com/kiegroup/drools-wb/pull/746 for 7.5.x

(cherry picked from commit 48781e9a3d1cf3c34aaa2b0c7685858682d4377b)

### CODE REVIEW

**Comment by manstis** [comment]
@etirelli Any objections this being merged (it's a correction of some text in the UI)?

**Comment by manstis** [comment]
@jomarko I'll wait for @etirelli to comment before merging.. IMO it should be merged since the issue was reported against the "New Getting started experience for Business Rules Application" EPIC in [RHDM](https://issues.jboss.org/browse/RHDM-183).

**Comment by jomarko** [comment]
@manstis agree, lets wait for another opinion.

**Comment by etirelli** [comment]
@manstis, you are correct.

**Comment by manstis** [comment]
OK thanks @etirelli 

Could you please arrange for https://issues.jboss.org/browse/RHDM-183 to have PM+ ACK?

**Pull request merged**
