### PR TITLE
AF-648 : Change Project from a folder in a repo to a repository

### PR DESCRIPTION
**Pull request by ederign**
Remove WorkspaceProjectContext from backend. Pass space as parameter.

### CODE REVIEW

**Comment by mbarkley** [comment]
Jenkins, please retest this.

**Comment by ederign** [comment]
@mbarkley @paulovmr @Rikkola Force pushed to rebase off master.

**Comment by ederign** [comment]
@mbarkley @paulovmr @Rikkola Force pushed to rebase off master.

**Comment by porcelli** [comment]
thank you also @tomasdavidorg @jhrcek for QE support

**Pull request merged**
