### PR TITLE
[DO NOT MERGE] Update the cheat sheet in Test Scenarios (Preview).

### PR DESCRIPTION
**Pull request by kkufova**
@danielezonca, please take a look. Just a quick fix to address the skip/null changes.

### CODE REVIEW

**Comment by kkufova** [comment]
jenkins please retest this

**Comment by kkufova** [comment]
@danielezonca, as Anna's PR is closed, I updated this one. Could you please check it one more time?

**Comment by danielezonca** [comment]
I think Anna is going to create a new PR based on the approach discussed with Porcelli. She probably just closed the old one too early :)

**Comment by kkufova** [comment]
@danielezonca, my understanding is that it may take a while to agree on the way how it can be done, so I thought we can have this in the meantime. :-)

**Pull request closed without merging**
