### PR TITLE
[DROOLS-3767] Reset "isEditing" status flag inside gridcell

### PR DESCRIPTION
**Pull request by yesamer**
https://issues.jboss.org/browse/DROOLS-3767

To avoid the described (and wrong) behaviour, a try - catch block was added in `ScenarioGridModel.edit()` method. Then, is ANY execption is catched, the "isEditing" status is reset as required.

About tests: in my opinion the current tests are enough: I don't know how to test the case where an exception is thrown during the process, feel free to give me some advice.

@danielezonca @gitgabrio  @kkufova please review.

### CODE REVIEW

**Comment by kie-ci3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by manstis** [comment]
Personally, IMO, a general _catch all_ error handler hides the problems and is probably more dangerous (long term) than fixing whatever issues cause DROOLS-3767 to be reported! That's my 2c... and not one to stand in the way of this PR.

**Comment by gitgabrio** [comment]
@manstis 
The original reason for that fix is that  BaseGridWidget.startEditingCell returns a boolean, but in the method flow  BaseCellSelectionManager.doEdit (that currently does not return nothing) is called, and BaseCellSelectionManager.edit always returns true, so there is no way to know if beginning editing was successful or not (for whatever reason).

Currently there is a bug with CollectionEditor when opening top-level list (with dmn-related scenario).
I'm already fixing that bug, but I realized that starting editing a cell *could* potentially throw some exception, maybe randomly due to some underlying transient issue (not so uncommon with client-side applications).
Having said that, I agree that whenever/wherever possible we must tackle and resolve the exception eventually thrown (as I 'm doing for the one in the CollectionEditor that cause this issue).

**Comment by kkufova** [comment]
@gitgabrio, @manstis, @yesamer, are we waiting for any additional changes here?

**Comment by gitgabrio** [comment]
@yesamer 
Fine for me

**Comment by gitgabrio** [comment]
@manstis
Hi! Could you please merge this, squashing commits? Thanks!

**Comment by manstis** [comment]
@gitgabrio Could you please approve before I merge.

**Comment by gitgabrio** [comment]
@manstis
I thought I did :smile:

**Pull request merged**
