### PR TITLE
[7.39.x] DROOLS-5537 : Performance issue - Test scenario creation for DMN & PMML model

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.redhat.com/browse/DROOLS-5537

### CODE REVIEW

**Comment by Rikkola** [comment]
I would hold the reviews since the master build is still being worked at. Just trying to get this green ASAP.

**Comment by Rikkola** [comment]
@jomarko @jstastny-cz @yesamer Hi, this is the same as for master.

**Comment by Rikkola** [comment]
Not here too.
`12:12:22  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project kie-wb-common-dmn-webapp-kogito-testing: Compilation failure`

jenkins please retest this

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by Rikkola** [comment]
Got the same error in a PR for master, hopefully it is temporal.

**Comment by mareknovotny** [comment]
the CI switched to older backup jobs for now so the pending CI comment is what is that result

**Comment by mareknovotny** [comment]
the build is green, waiting on  @jomarko review ;) now

**Comment by Rikkola** [comment]
@kiegroup/gatekeepers Can I get a merge please.

**Pull request merged**
