### PR TITLE
[RHPAM-2089] Added missing dependency to test guided decision table

### PR DESCRIPTION
**Pull request by danielezonca**
@kkufova @Rikkola @gitgabrio 

https://issues.jboss.org/browse/RHPAM-2089

### CODE REVIEW

**Comment by danielezonca** [comment]
@kiegroup/gatekeepers 
Can you please squash and merge this?

**Comment by manstis** [comment]
@danielezonca Not one to be picky... but should a test somewhere not have been updated too!?

**Comment by danielezonca** [comment]
@manstis 
Done :)

**Comment by danielezonca** [comment]
@manstis 
Can you please squash and merge?

**Pull request merged**
