### PR TITLE
KOGITO-879 KOGITO-880 KOGITO-881: State Control API (undo/redo)

### PR DESCRIPTION
**Pull request by pefernan**
Adding missing deps to showcase,

@manstis do you mind take a look?

This is part of an ensemble, please merge with:
https://github.com/kiegroup/kogito-tooling/pull/66
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1195
https://github.com/kiegroup/appformer/pull/894
https://github.com/kiegroup/kie-wb-common/pull/3156
https://github.com/kiegroup/jbpm-wb/pull/1414
https://github.com/kiegroup/drools-wb/pull/1310
https://github.com/kiegroup/kie-wb-distributions/pull/1013

### CODE REVIEW

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by jomarko** [comment]
Please could anyone clarify why this is needed in non kogito module?

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by tiagobento** [comment]
FDB passed. See https://github.com/kiegroup/appformer/pull/894

**Pull request merged**
