### PR TITLE
Adding dashbuilder-services-api to fix broken master compilation

### PR DESCRIPTION
**Pull request by yesamer**

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins execute full downstream production build

**Comment by danielezonca** [comment]
@Ginxo 
The build failed with
`groovy.lang.MissingPropertyException: No such property: ADDITIONAL_LABEL for class: groovy.lang.Binding`
Can you please verify the pipeline?

**Comment by yesamer** [comment]
@jomarko That PR introduces usage of some class inside `dashbuilder-services-api` (eg. https://github.com/kiegroup/appformer/pull/933/files#diff-29de0f51e9f60966e5fb90635a4a7812R29). 
Probably this explain the behavior of the enforcer

**Comment by Ginxo** [comment]
Jenkins execute full downstream production build

**Comment by Ginxo** [comment]
Jenkins execute full downstream production build

**Pull request merged**
