### PR TITLE
[7.3.x] GUVNOR-3145: Add column\Edit column buttons should be disabled in new Graph

### PR DESCRIPTION
**Pull request by karreiro**
Cherry picked from https://github.com/kiegroup/drools-wb/pull/584

### CODE REVIEW

**Comment by manstis** [comment]
Please let me know when green and I'll merge.

**Comment by manstis** [comment]
It's also good to see you've future proofed your branch by calling it ```GUVNOR-3145-7.5.x``` :-)

**Comment by karreiro** [comment]
Yeah, I just noticed that! :S

**Comment by karreiro** [comment]
@manstis it's green :-)

**Comment by manstis** [comment]
Thanks @karreiro

**Pull request merged**
