### PR TITLE
DROOLS-2565: [DMN Editor] Move showcase webapp to 'project' based instead of 'standalone'

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-2565

I decided to integrate DMN into ```drools-wb-webapp``` rather than create a completely new "standalone".

### CODE REVIEW

**Comment by manstis** [comment]
Part of an ensemble:

- https://github.com/kiegroup/kie-wb-common/pull/1975
- https://github.com/kiegroup/drools-wb/pull/888

**Comment by karreiro** [comment]
@manstis I just tried this PR locally and I got this error (by running drools-wb with gwt:run):
demo
..and this error:
```
Uncaught exception: Exception caught: No proxy provider found for bindable type: org.kie.workbench.common.dmn.api.definition.v1_1.BusinessKnowledgeModel Caused by: No proxy provider found for bindable type: org.kie.workbench.common.dmn.api.definition.v1_1.BusinessKnowledgeModel
```
Am I missing something?

**Comment by manstis** [comment]
I had that error the first time I ran it... but deletion of /tmp/manstis (errai temporary folder) and mvn clean process-resources gwt:run worked thereafter.

**Comment by manstis** [comment]
@jomarko You've already approved.. just need @karreiro to pull his socks up! ;-)

**Pull request merged**
