### PR TITLE
[7.52.x] DROOLS-6056 : GDST to XLS conversion should wrap String values in a list associated with 'in' with quotes

### PR DESCRIPTION
**Pull request by Rikkola**
(cherry picked from commit 62cffbefc8e82e4165686064f7c8029bd39ab02a)

[DROOLS-6056](https://issues.redhat.com/browse/DROOLS-6056)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by yesamer — APPROVED** [review]

**Comment by Rikkola** [comment]
jenkins run fdb

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
Jenkins retest this

**Review by jstastny-cz — APPROVED** [review]
LGTM.

**Comment by Rikkola** [comment]
Jenkins retest this

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by Rikkola** [comment]
@kiegroup/gatekeepers Can I get a merge please.

**Pull request merged**
