### PR TITLE
Drools 4275 - Drools-wb webapp does not start

### PR DESCRIPTION
**Pull request by gitgabrio**
@kkufova @mbiarnes @danielezonca @mareknovotny 

Restored original (working) pom.

@mbiarnes Please verify the reason why you modified it - on my local machine it compile and starts without those modifications

### CODE REVIEW

**Comment by mbiarnes** [comment]
@gitgabrio if this works on Jenkins OK. The less changes we have the better. 
For me it didn't wok locally nor on Jenkins. So I skipped the enforcer.

**Comment by gitgabrio** [comment]
jenkins please retest this

**Comment by danielezonca** [comment]
All 41 failures are related to a wrong `beans.xml` format in `uberfire-api` that has been fixed by this PR https://github.com/kiegroup/appformer/pull/721 so let's wait that PR to be merged before rerun the build.

`org.drools.workbench.screens.drltext.backend.server.DRLTextEditorServiceImplCDITest.testValidDSRLFile
org.drools.workbench.screens.drltext.backend.server.DRLTextEditorServiceImplCDITest.testFunctionInDRL
org.drools.workbench.screens.drltext.backend.server.DRLTextEditorServiceImplCDITest.testInvalidContentDRL
org.drools.workbench.screens.drltext.backend.server.DRLTextEditorServiceImplCDITest.testLoadContent
org.drools.workbench.screens.drltext.backend.server.DRLTextEditorServiceImplCDITest.testInvalidDSRLFile
org.drools.workbench.screens.drltext.backend.server.DRLTextEditorServiceImplCDITest.testDSLCompinedWithPureDRL
org.drools.workbench.screens.drltext.backend.server.DRLTextEditorServiceImplCDITest.testDRLFileWithGlobalVariable
org.drools.workbench.screens.drltext.backend.server.DRLTextEditorServiceImplCDITest.testDRLFileWithExplicitNonExistingImport
org.drools.workbench.screens.drltext.backend.server.DRLTextEditorServiceImplCDITest.testDRLFileWithExplicitImport
org.drools.workbench.screens.drltext.backend.server.DRLTextEditorServiceImplCDITest.testValidDRLFileWithTwoRules
org.drools.workbench.screens.drltext.backend.server.DRLTextEditorServiceImplCDITest.testValidDRLFile
org.drools.workbench.screens.drltext.backend.server.DRLTextEditorServiceImplCDITest.testLoadClassFields
org.drools.workbench.screens.drltext.backend.server.DRLTextEditorServiceImplCDITest.testNumericalTypes
org.drools.workbench.screens.drltext.backend.server.DRLTextEditorServiceImplCDITest.testDRLFileWithUnknownGlobalVariable
org.drools.workbench.screens.drltext.backend.server.DRLTextEditorServiceImplCDITest.testDRLFileWrongConstructor
org.drools.workbench.screens.dtablexls.backend.server.DecisionTableXLSServiceImplCDITest.testValidateMultiplePatterns
org.drools.workbench.screens.dtablexls.backend.server.DecisionTableXLSServiceImplCDITest.testFromAccumulate
org.drools.workbench.screens.dtablexls.backend.server.DecisionTableXLSServiceImplCDITest.testValidateColumnsNotInStandardOrder
org.drools.workbench.screens.dtablexls.backend.server.DecisionTableXLSServiceImplCDITest.testConvertFunctionAndBigDecimal
org.drools.workbench.screens.dtablexls.backend.server.DecisionTableXLSServiceImplCDITest.testConvertStaticFields
org.drools.workbench.screens.dtablexls.backend.server.DecisionTableXLSServiceImplCDITest.testValidateFunctionAndBigDecimal
org.drools.workbench.screens.enums.backend.server.EnumServiceImplCDITest.testValidate
org.drools.workbench.screens.enums.backend.server.EnumServiceImplCDITest.testValidateWrongSyntax
org.drools.workbench.screens.enums.backend.server.indexing.EnumIndexVisitorCDITest.testDependentEnumIndexing
org.drools.workbench.screens.guided.dtable.backend.server.GuidedDecisionTableEditorServiceImplCDITest.testTimeInTimeZones
org.drools.workbench.screens.guided.dtable.backend.server.GuidedDecisionTableEditorServiceImplCDITest.testFromAccumulate
org.drools.workbench.screens.guided.dtable.backend.server.GuidedDecisionTableEditorServiceImplCDITest.testFunctionFromDrl
org.drools.workbench.screens.guided.rule.backend.server.GuidedRuleEditorServiceImplCDITest.testAbbreviatedCondition
org.drools.workbench.screens.guided.rule.backend.server.GuidedRuleEditorServiceImplCDITest.testValidateRuleThatInherit
org.drools.workbench.screens.guided.rule.backend.server.GuidedRuleEditorServiceImplCDITest.testValidateSalienceAttributeInvalidNumber
org.drools.workbench.screens.guided.rule.backend.server.GuidedRuleEditorServiceImplCDITest.testValidateRuleAlphabeticallyComparesStrings
org.drools.workbench.screens.guided.rule.backend.server.GuidedRuleEditorServiceImplCDITest.testValidateTimeSpecificAttributes
org.drools.workbench.screens.guided.rule.backend.server.GuidedRuleEditorServiceImplCDITest.testValidateSalienceAttribute
org.drools.workbench.screens.guided.rule.backend.server.GuidedRuleEditorServiceImplCDITest.testValidateTimeSpecificAttributesInvalidTimer
org.drools.workbench.screens.guided.rule.backend.server.GuidedRuleEditorServiceImplCDITest.testValidateTimeSpecificAttributesCron
org.drools.workbench.screens.guided.rule.backend.server.GuidedRuleEditorServiceImplCDITest.testValidateDateEffectiveAttribute
org.drools.workbench.screens.guided.rule.backend.server.GuidedRuleEditorServiceImplCDITest.testValidateDateExpiresAttribute
org.drools.workbench.screens.guided.rule.backend.server.GuidedRuleEditorServiceImplCDITest.testValidateRuleThatInheritNonExistingRule
org.drools.workbench.screens.guided.template.server.GuidedRuleTemplateEditorServiceImplCDITest.testValidateAndLoad
org.drools.workbench.screens.guided.template.server.GuidedRuleTemplateEditorServiceImplCDITest.testValidate
org.drools.workbench.screens.guided.template.server.GuidedRuleTemplateEditorServiceImplCDITest.testLoadContent`

**Comment by yesamer** [comment]
jenkins please retest this

**Comment by manstis** [comment]
@mbiarnes This PR fails due to an enforcer rule:
```
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-direct-dependencies) @ drools-wb-webapp ---
[INFO] Analyze dependencies of artifact 'org.drools:drools-wb-webapp:war:7.24.0-SNAPSHOT'.
Downloading from jboss-developer-repository-group: https://repository.jboss.org/nexus/content/groups/developer/org/drools/drools-wb-webapp/7.24.0-SNAPSHOT/maven-metadata.xml
Downloading from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public/org/drools/drools-wb-webapp/7.24.0-SNAPSHOT/maven-metadata.xml
Downloading from jboss-developer-repository-group: https://repository.jboss.org/nexus/content/groups/developer/org/drools/drools-wb-webapp/7.24.0-SNAPSHOT/drools-wb-webapp-7.24.0-SNAPSHOT.war
Downloading from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public/org/drools/drools-wb-webapp/7.24.0-SNAPSHOT/drools-wb-webapp-7.24.0-SNAPSHOT.war
[ERROR] Unable to resolve artifact 'org.drools:drools-wb-webapp:war:7.24.0-SNAPSHOT'!
org.apache.maven.artifact.resolver.ArtifactNotFoundException: Could not find artifact org.drools:drools-wb-webapp:war:7.24.0-SNAPSHOT in jboss-developer-repository-group (https://repository.jboss.org/nexus/content/groups/developer/)
```
Do you have any idea why the enforcer rule is trying to find the WAR that is trying to be built!?!

**Comment by mbiarnes** [comment]
@manstis Sorry. I don't understand this neither. Why is the enforcer trying to download something before it is built?

**Comment by gitgabrio** [comment]
@manstis @mbiarnes @danielezonca 
The enforcer is actually meant to work that way. Reading from documentation (https://maven.apache.org/enforcer/maven-enforcer-plugin/enforce-mojo.html):
"_enforcer:enforce
...
Binds by default to the lifecycle phase: validate._"

**validate** is the very first maven phase (http://maven.apache.org/ref/3.6.1/maven-core/lifecycles.html)

Moreover, the specific implementation (https://github.com/Scout24/illegal-transitive-dependency-check) by default use artifacts from repos (local or remote)
"_By default the rule will resolve the currently analyzed artifact in the Maven repository. In case the enforcer-plugin runs in a phase compiled classes are available in the target folder (e.g. verify) artifact-resolving can be avoided by setting parameter useClassesFromLastBuild to true._"

Fix we have done with @yesamer is
1) bind the enforce-direct-dependencies to the **verify** phase (soon before install)
2) configure **IllegalTransitiveDependencyCheck** to use compiled classes (and not repo's artifacts)

**Comment by mareknovotny** [comment]
@gitgabrio @mbiarnes I think that enforcer plugin configuration change should be useful to have in kie-parent.

**Comment by gitgabrio** [comment]
> @gitgabrio @mbiarnes I think that enforcer plugin configuration change should be useful to have in kie-parent.

Yes, I think it should. But for the moment being we need to close that as soon as possible.

**Comment by mbiarnes** [comment]
@mareknovotny @gitgabrio do I see right that we don't have defined in kie-parent a <phase>validate</phase> ? Normally- if not defined a <phase> - the enforcer is bound to the phase of validate?

**Comment by gitgabrio** [comment]
> @mareknovotny @gitgabrio do I see right that we don't have defined in kie-parent a validate ? Normally- if not defined a - the enforcer is bound to the phase of validate?

"Normally- if not defined a - the enforcer is bound to the phase of validate?" -> Yes. That's why I put reference to documentation and specifically quoted that.

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by gitgabrio** [comment]
jenkins please retest this

**Comment by gitgabrio** [comment]
jenkins please retest this

**Comment by ederign** [comment]
> @gitgabrio @mbiarnes I think that enforcer plugin configuration change should be useful to have in kie-parent.

Guys, before applying this please build appformer repo.

At least locally I'm getting this on appformer-js-brigde: 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:unpack (unpack-appformer-js) on project appformer-js-bridge: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98. -> [Help 1]

**Comment by gitgabrio** [comment]
> > @gitgabrio @mbiarnes I think that enforcer plugin configuration change should be useful to have in kie-parent.
> 
> Guys, before applying this please build appformer repo.
> 
> At least locally I'm getting this on appformer-js-brigde:
> 
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:unpack (unpack-appformer-js) on project appformer-js-bridge: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98. -> [Help 1]

@ederign 
The modification we done does two things
1) move execution of transitive dependency check (and only this - **not the whole enforcer**) to _verify_ phase (soon before _install_) 
2) uses locally built classes instead of artifact from (local or remote) repo

The dependency plugin usually runs before ( https://maven.apache.org/plugins/maven-dependency-plugin/unpack-mojo.html ) at _process-sources_ phase, so I can not see a relationship between them.
But the current root configuration of enforcer is plainly broken, and has worked all that time only for a series of coincidences (I may explain them if you wish, and I think it could be useful to know). The same could easily be true for other things - please check carefully the appformer pom configuration, what and how the goals are configured, and experiment with "clean" local repo (that's how we get to understood that issue)

**Pull request merged**
