### PR TITLE
DROOLS-4986: Change dmn model does not update model name and namespace

### PR DESCRIPTION
**Pull request by yesamer**
Changes introduced in this PR:
- When changing DMN reference in the Setting dock, DMN Name and DMN Namespace are now updated (BC and Kogito);
- When changing DMN reference in the Setting dock, the Fact list in the Test Tools dock is now updated (BC and Kogito);
- When changing DMN reference in the Setting dock a Validation is performed (BC only);

Screencast from 02-02-2021 11_36_37 AM

**JIRA**: https://issues.redhat.com/browse/DROOLS-4986

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins run fdb

**Review by jstastny-cz — APPROVED** [review]
LGTM, I've run regression tests for affected area, all seems good.
The original issue is fixed too.

**Comment by yesamer** [comment]
jenkins run fdb

**Review by karreiro — APPROVED** [review]
Thank you, @yesamer LGTM!

**Pull request merged**
