### PR TITLE
DROOLS-2077: Turn on static code analysis

### PR DESCRIPTION
**Pull request by jomarko**
This PR is dependent on all _Prepare module_ PRs which need to be merged before.

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

@jomarko Running again, now the other PRs are merged. Please let me know when green.

**Comment by jomarko** [comment]
@manstis sure, thanks.

**Comment by jomarko** [comment]
@manstis tests passed.

**Comment by manstis** [comment]
+1 Approved.. forgot to do so before merging (and I can no longer use the _review_ approach).

**Comment by jomarko** [comment]
@manstis we all will miss your _License please_, had you this approach in mind?

**Comment by manstis** [comment]
@jomarko TBH I had nothing in mind.. but what you've done here should prevent me from typing those words ever again!

**Comment by jomarko** [comment]
@manstis sure, I hope it will brings us just positive things.

**Pull request merged**
