### PR TITLE
KOGITO-2060: Order of facts of Test Tools in Kogito and BC is different

### PR DESCRIPTION
**Pull request by yesamer**
@danielezonca @jstastny-cz  Can you please review and test it?

As described into the ticket, instance's properties are ordered in different way in BC and Kogito.
In Kogito, the applied order is the same you can find inside the `.dmn` file, while for BC I don't have idea of the applied ordering.
To have the same order, the code now sorts the properties (natural order) when populating Test Tools Dock

Screenshot from 2020-07-08 11-42-07

In addition, I applied the same sorting when creating **new** DMN type scenario, which means, during grid creation, the columns will be added following the same order present in Test Tool dock.

Screenshot from 2020-07-08 12-00-33

https://issues.redhat.com/browse/KOGITO-2060

### CODE REVIEW

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
@jstastny-cz Can you please test it?

**Comment by jstastny-cz** [comment]
jenkins execute full downstream build

**Comment by yesamer** [comment]
@karreiro can you please merge It?

**Pull request merged**
