### PR TITLE
[7.5.x] BAQE-322 Cover validation of the guided rule with inheritance

### PR DESCRIPTION
**Pull request by jomarko**
This PR cover valiudation of the guided rule asset while focus on the guided rule that inherit from another guided rule.

This is corollary of #751 .

### CODE REVIEW

**Comment by manstis** [comment]
@jomarko I've approved (as it's a cherry-pick to 7.5.x) however I did notice (and it's probably the same in the orginal PR) that the paths for "Guided Rules" reference "dtables". I wonder whether you want to improve the separation and move RDRL files to different packages/projects?

**Comment by jomarko** [comment]
@manstis makes sense, will update also master

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
@manstis ready for merge when you have free hand.

**Pull request merged**
