### PR TITLE
Remove unused dependencies from drools-wb-enum-editor-backend module

### PR DESCRIPTION
**Pull request by jomarko**
@manstis may I ask you for review? This is related to the module you touched in #1179

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by yesamer** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
This PR became out of date and it is not needed anymore.

**Pull request closed without merging**
