### PR TITLE
GUVNOR-3277: [Guided Decision Table] Pattern and Field can be bound to the same name

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/GUVNOR-3277

---

Thank you for the comments in the JIRA @jomarko and @manstis :-)

---

Before:
before

After:
after

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins please execute full downstream build.

**Comment by karreiro** [comment]
Jenkins please execute full downstream build.

**Comment by jomarko** [comment]
@karreiro you read my mind, thank you, trying the build manually right now.

**Comment by jomarko** [comment]
@manstis all credits belongs to @karreiro . I did just review :)

**Comment by karreiro** [comment]
Thanks for the review @manstis and @jomarko :-) Changes applied.

**Pull request merged**
