### PR TITLE
KOGITO-2773: BC - Kogito generated scesim files improved compatibility

### PR DESCRIPTION
**Pull request by yesamer**
**JIRA**: https://issues.redhat.com/browse/KOGITO-2773

This PR improves compatibility between VSCode (Kogito) generated scesim files and Business Central ones.
The case managed here, is when a DMN Type has constraints. 
In BC, this case in managed creating a new "Anonymous" data type with the "real" type put inside baseType fields.
In Kogito the real type is directly assigned.
This results to generate a Kogito generated scesim file not compatible with BC, where data types with constraints are present.
To fix the issue, I replicated the same behavior present in BC in Kogito: this means to add `baseType` fields and populate it when constraints are present.

<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by danielzhe — APPROVED** [review]
Good job! I didn't found any issue. Thank you, @yesamer !

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
jenkins retest this please

**Review by jstastny-cz — APPROVED** [review]
LGTM.

SonarCloud complaining about the increased complexity of createFactModelTreeForComposite caused by adding the ternary operator ?: into else branch on line 567. Having said that - the limit has been probably overcome already before the changes here.

**Review by karreiro — APPROVED** [review]

**Pull request merged**
