### PR TITLE
DROOLS-3562: Values are getting missed/changed from guided rule template if we perform sort operation on any column & try to save it

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-3562 specifically [this](https://issues.jboss.org/browse/DROOLS-3562?focusedCommentId=13696576&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13696576).

Unfortunately after much trying I've been unable to write a Unit Test for this :-(

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
Smallest reproducer is [here](https://issues.jboss.org/browse/RHDM-827?focusedCommentId=13696608&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13696608).

**Comment by Rikkola** [comment]
I think it can go in as it is. You probably wouldn't have made a change in a bigger change either and if this code is moved anywhere the change moves with the code line.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Replaced by https://github.com/kiegroup/drools-wb/pull/1076 as a new JIRA was required.

**Pull request closed without merging**
