### PR TITLE
DROOLS-4249: Test classes generation was done

### PR DESCRIPTION
**Pull request by jomarko**
Dependent on #1306

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
@jomarko The test failed, it expects a `Long` where it has a `Int`

**Comment by jomarko** [comment]
@yesamer test should be fixed now

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge

**Pull request merged**
