### PR TITLE
DROOLS-2229 : Error shown every time GDT editor opened in Firefox and IE11

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-2229

(cherry picked from commit ecb5767c5df936a239b14104a17cc751875488a6)

### CODE REVIEW

**Comment by Rikkola** [comment]
Looks like I need to rebuild everything to get this working locally. Maybe this PR builds it faster.

**Comment by manstis** [comment]
@Rikkola Please let me know when green and I'll merge.

**Comment by Rikkola** [comment]
@manstis Ok. All green now.

**Comment by jomarko** [comment]
Trying to build locally, will approve once checked.

**Comment by jomarko** [comment]
I am not able to build locally the 7.5.x branch

jenkins execute full downstream build

**Comment by Rikkola** [comment]
@jomarko Yeah, I had the same problems.

**Comment by Rikkola** [comment]
@manstis Thank you and good morning.

**Pull request merged**
