### PR TITLE
DROOLS-2103: Test scenario using Numerical types

### PR DESCRIPTION
**Pull request by jomarko**
Dependent on #703

### CODE REVIEW

**Comment by manstis** [comment]
@jomarko This PR needs some love before we review :-)

**Comment by jomarko** [comment]
@manstis PR updated with my love.

**Comment by jomarko** [comment]
@manstis it could be safe to get this in.

**Comment by manstis** [comment]
@jomarko Hopefully "it _should_ be safe"... and not "_could_ be safe" :-)

**Pull request merged**
