### PR TITLE
[7.3.x] PLANNER-823: ScoreHolder support does not work in Guided Decision Tables

### PR DESCRIPTION
**Pull request by mcimbora**
Part of:
https://github.com/kiegroup/optaplanner-wb/pull/198
https://github.com/kiegroup/drools/pull/1412
https://github.com/kiegroup/drools-wb/pull/571

### CODE REVIEW

**Comment by mcimbora** [comment]
@manstis Just a backport of a master branch fix (https://github.com/kiegroup/optaplanner-wb/pull/188)

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by manstis** [comment]
@mcimbora If this is a cherry-pick could you make the reviewers' life easier by stating so :-)

**Comment by jomarko** [comment]
As this is cherry-pick, I am not going to review again because I did when it was opened for 7.2.x branch. I just wanted see passing tests.

**Comment by mcimbora** [comment]
@manstis I mentioned in the first comment it's a backport of a master branch fix (with a link). I'll try to be more specifix next time ;-)

**Comment by mcimbora** [comment]
@jomarko @manstis It might take a while to get the build green, our kie-build-helper-jenkins-plugin does not support 7.3.x branch for now, created a fix in https://github.com/kiegroup/kie-build-helper-jenkins-plugin/pull/5

**Comment by manstis** [comment]
@mcimbora You're right. Sorry.

**Comment by mcimbora** [comment]
Jenkins retest this.

**Pull request merged**
