### PR TITLE
DROOLS-5394: Coverage Report Improvements (CSV File)

### PR DESCRIPTION
**Pull request by yesamer**
@danielezonca @dupliaka Can you please test and review?

Proposed solution for https://issues.redhat.com/browse/RHPAM-2616 is to put the same data shown on Coverage Report inside the generated CSV Report file.
This means to add following data:
- Overall Stats (Available rules, executed rules, coverage percentage);
- Rules counters

Screenshot from 2020-06-04 14-00-57

Related server side PR: https://github.com/kiegroup/drools/pull/2989

https://issues.redhat.com/browse/DROOLS-5394
https://issues.redhat.com/browse/RHPAM-2616

### CODE REVIEW

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by dupliaka** [comment]
jenkins execute full downstream build

**Comment by yesamer** [comment]
> @yesamer I might not clearly understand the columns in the report. So let's say I try the Traffic Violation sample project, precisely the `Violation Scenarios.scesim` file.
> 
> Then I export the report and I see following contents:
> 
> ```
> AVAILABLE RULES,RULES FIRED,PERCENTAGE OF RULES FIRED
> 2,2,100.0
> 
> RULE,NUMBER OF TIMES
> Fine,5
> Should the driver be suspended?,5
> 
> SCENARIO INDEX,SCENARIO NAME,RESULT INDEX,RESULT,LEVEL
> 1,Above speed limit: 10km/h and 30 km/h,1,Fine,SUCCEEDED
> 1,Above speed limit: 10km/h and 30 km/h,2,Should the driver be suspended?,SUCCEEDED
> 2,Above speed limit: more than 30 km/h,1,Fine,SUCCEEDED
> 2,Above speed limit: more than 30 km/h,2,Should the driver be suspended?,SUCCEEDED
> 3,Parking violation,1,Fine,SUCCEEDED
> 3,Parking violation,2,Should the driver be suspended?,SUCCEEDED
> 4,DUI violation,1,Fine,SUCCEEDED
> 4,DUI violation,2,Should the driver be suspended?,SUCCEEDED
> 5,Driver suspended,1,Fine,SUCCEEDED
> 5,Driver suspended,2,Should the driver be suspended?,SUCCEEDED
> ```
> 
> So my questions would be:
> 
> * What is the purpose of the last two columns? Why RESULT contains name of the decision and what is the meaning of LEVEL column?
> * Depending on the above - should the value of LEVEL field change based on the test run results? (it does not currently).
> * I think the csv report should talk about `Decisions` not `Rules` in this case (testing DMN models)

@jstastny-cz Thank you for your review. 
According to your comments, I see you tested a DMN Scenario case. And you're right, the headers labels seems meaningless for that case. The point is these titles fit correctly in case of a RULE tests scenario, where RULES are evaluated.
So, I defined 2 different labels set 1 for the RULE case (which are basically the current labels) and another set for DMN case.
About the LEVEL column: it is a label returned by the engine, which is different in DMN and RULE cases. We can improve this aspect as well, but I propose to manage it in another ticket.

**Comment by yesamer** [comment]
@jstastny-cz Based on your observations, I applied this change:
-  I substituted `LEVEL` with `RESULT`: NOT_EVALUATED, EVALUATING, SUCCEEDED, SKIPPED, FAILED for _DMN Test Scenarios_, while _Rule Test Scenario_ manage only SUCCEEDED value. 
- `LEVEL` it's now merged with `RESULT`, only in the case an error is thrown during decision evaluation. eg in case of no error, you will see: SUCCEEDED only, in case on error: WARN: SKIPPED or ERROR: FAILED
These change are mostly applied on backend side:https://github.com/kiegroup/drools/pull/2989

**DMN Test Scenario Case:**

`AVAILABLE DECISIONS | DECISIONS FIRED | PERCENTAGE OF DECISIONS FIRED |   |  
-- | -- | -- | -- | --
2 | 2 | 100 |   |  
  |   |   |   |  
DECISION | NUMBER OF TIMES |   |   |  
Should the driver be suspended? | 5 |   |   |  
Fine | 5 |   |   |  
  |   |   |   |  
TEST SCENARIO INDEX | TEST SCENARIO NAME | DECISION INDEX | EVALUATED DECISION | RESULT
1 | Above speed limit: 10km/h and 30 km/h | 1 | Should the driver be suspended? | SUCCEEDED
1 | Above speed limit: 10km/h and 30 km/h | 2 | Fine | SUCCEEDED
2 | Above speed limit: more than 30 km/h | 1 | Should the driver be suspended? | SUCCEEDED
2 | Above speed limit: more than 30 km/h | 2 | Fine | SUCCEEDED
3 | Parking violation | 1 | Should the driver be suspended? | SUCCEEDED
3 | Parking violation | 2 | Fine | SUCCEEDED
4 | DUI violation | 1 | Should the driver be suspended? | SUCCEEDED
4 | DUI violation | 2 | Fine | SUCCEEDED
5 | Driver suspended | 1 | Should the driver be suspended? | SUCCEEDED
5 | Driver suspended | 2 | Fine | SUCCEEDED`

**Rule Test Scenario Case:**

`AVAILABLE RULES | RULES FIRED | PERCENTAGE OF RULES FIRED |   |  
-- | -- | -- | -- | --
3 | 3 | 100 |   |  
  |   |   |   |  
RULE | NUMBER OF TIMES |   |   |  
Book is unavailable if the number of copies is zero (com) | 1 |   |   |  
Book does not exist if the number of copies is less then zero (com) | 1 |   |   |  
Book is available if the number of copies is more than zero (com) | 1 |   |   |  
  |   |   |   |  
TEST SCENARIO INDEX | TEST SCENARIO NAME | RULE INDEX | EVALUATED RULE | RESULT
1 | First | 1 | Book is available if the number of copies is more than zero (com) | SUCCEEDED
2 | Second | 1 | Book is unavailable if the number of copies is zero (com) | SUCCEEDED
3 | Third | 1 | Book does not exist if the number of copies is less then zero (com) | SUCCEEDED`

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
@jstastny-cz Now it's ready.

**Comment by yesamer** [comment]
@kiegroup/gatekeepers Can you please merge it?

**Pull request merged**
