### PR TITLE
[DROOLS-2676] Input actual data into data fields

### PR DESCRIPTION
**Pull request by danielezonca**
Enabled inline editing of the grid for cells and headers (only not static strings) with real time model synchronization.
Double click to edit and lost focus to flush data to model. 

@Rikkola @gitgabrio @jsoltes

### CODE REVIEW

**Comment by kkufova** [comment]
I will take a look instead of @jsoltes, as he's on a long-term leave from September 19th.

**Comment by manstis** [comment]
@danielezonca OK to squash when merged?

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
@kkufova 
The bug should be fixed with latest commit, can you check please?

**Comment by danielezonca** [comment]
@kkufova 
Fixed :)

**Comment by danielezonca** [comment]
@manstis 
Can you please squash and merge?

Thanks

**Pull request merged**
