### PR TITLE
DROOLS-5291 & DROOLS-5223: Managing empty and invalid scesim file

### PR DESCRIPTION
**Pull request by yesamer**
@dupliaka @danielezonca can you please review and test?

If you try to load an empty or invalid `scesim` file, editor will show an error remaining stuck with the loading popup. 
With this patch, an error will be shown and the editor automatically closed.

Screencast-from-06-09-2020-10_59_42-AM

Related Backend PR: https://github.com/kiegroup/drools/pull/2940

https://issues.redhat.com/browse/DROOLS-5223
https://issues.redhat.com/browse/DROOLS-5291

### CODE REVIEW

**Comment by dupliaka** [comment]
- [ ] Corrupted files close and error message appears

- [ ] Empty file files close and error message appears

? Should we keep the invalid files when we cannot delete nor operate on them

**Comment by yesamer** [comment]
@dupliaka @jstastny-cz I forgot to link the backend part of the PR. Please include it to evaluate the empty case as well.

**Comment by dupliaka** [comment]
>     * [x]  Corrupted files close and error message appears
> 
>     * [ ]  Empty file files close and error message appears
> 
> 
> ? Should we keep the invalid files when we cannot delete nor operate on them

As it has been discussed with @yesamer. The idea of leaving invalid files is to keep the file and open it in the XML editor that is planned to be implemented next release.

**Comment by yesamer** [comment]
@dupliaka Can you please approve the BackEnd part as well? https://github.com/kiegroup/drools/pull/2940

**Comment by danielezonca** [comment]
@yesamer 
I don't think it is the proper solution: if you have a broken scesim file and you want to remove it you have to open the editor first (ok you can use git but it is not user friendly :) ) so now it will not stuck with loading indicator but it is still not possible to remove the broken file.
Wdyt?

**Comment by yesamer** [comment]
> @yesamer
> I don't think it is the proper solution: if you have a broken scesim file and you want to remove it you have to open the editor first (ok you can use git but it is not user friendly :) ) so now it will not stuck with loading indicator but it is still not possible to remove the broken file.
> Wdyt?

Good point. Removed automatic closing of the file.

**Comment by danielezonca** [comment]
@yesamer 
Can you please add a screenshot/video of the new behavior (without closing the file)?

**Comment by yesamer** [comment]
> @yesamer
> Can you please add a screenshot/video of the new behavior (without closing the file)?
> 
> EDIT: I'm mainly interested to toolbar and buttons: for example, is `Save` button active? What is the result if I try to save? Same for rename etc

I was thinking the same: In case of empty grid we would have a lot of minor details to manage: buttons, docks, editor space (if you try to click inside the empty editor, an exception is thrown).

Therefore my proposal are:
- Extend this PR implementing the ACE editor to be loaded in this case, in the same way BPMN Editor and DMN Editor currently do;
- Restore the Automatic close, merge it and implement the ACE editor in a second PR. Of course, it will be not possible to delete the file, but it's an improvement in any case. And consider we can delete it with the current behavior as well.
Both are fine for me, considering isn't a critical use case. I just would avoid to manage an "empty editor" status.

**Comment by danielezonca** [comment]
@yesamer 
Both proposals are fine for me, I don't know how hard could be to add ACE editor fallback so up to you to decide if you prefer to use a different PR or not
Let me know so I can approve or wait

**Comment by yesamer** [comment]
@danielezonca I decided for the the second option. Please consider kogito-tooling team asked to implement ACE editor for Kogito version. I think it should be possible.
Please merge it when build is green.

**Comment by yesamer** [comment]
Failure on `Pull Request Execution` not related to this PR
`10:24:48 [INFO] OptaPlanner Quarkus Jackson - Integration tests .... FAILURE [  2.475 s]`

@danielezonca Can you please merge this and https://github.com/kiegroup/drools/pull/2940 ?

**Pull request merged**
