### PR TITLE
BAPL-839 (for upstream 7.5.x): Updated Template Key help text in GDT and guided rule designers 

### PR DESCRIPTION
**Pull request by sterobin**
Cherry-picked from BAPL-839-master. Details in [JIRA](https://issues.jboss.org/browse/BAPL-839).

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
Same comment as in #788

**Comment by sterobin** [comment]
@mbiarnes , the master PR for this change (#788) worked fine, but this 7.5.x PR has failed for [this reason](https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/drools-wb-pullrequests-7.5.x/46/testReport/). Any ideas what that might mean or ways to retry?

**Comment by manstis** [comment]
Jenkins please retest this.

@sterobin the failure is not @mbiarnes concern.. looks false-negative to me.. let's try again.

@jomarko It looks like the general consensus is to open a new JIRA correcting various "tool tip" issues on the Guided Rule Editor dialogues. Perhaps approve these PRs and await the new JIRA to come round.

**Comment by sterobin** [comment]
Oh, sorry @manstis , I thought I saw that you already tried re-testing and still it failed. My bad, @mbiarnes .

**Pull request merged**
