### PR TITLE
DROOLS-2263: Unexpected results in GDST when using enumerations with commas - info

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-2263

@manstis @jomarko 
I was planning to add this to the docs, but there is no good spot for it there and we already had the info panel in the Guided DTable editor.

### CODE REVIEW

**Comment by jomarko** [comment]
@Rikkola maybe worth to cherry-pick into 7.5.x also.

**Comment by Rikkola** [comment]
@jomarko Sure, waited for approvals on this one.

**Comment by manstis** [comment]
@Rikkola Please let me know when this is "good to go"

**Comment by Rikkola** [comment]
@manstis It is good to go. I was waiting for your and @jomarko's approvals :)

**Pull request merged**
