### PR TITLE
[7.52.x] DROOLS-6071 backport

### PR DESCRIPTION
**Pull request by mareknovotny**
**Thank you for submitting this pull request**

backport of #1500 for https://issues.redhat.com/browse/DROOLS-6071

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by jomarko** [comment]
@mareknovotny number of changes and conflicts suggest, this is not proper backport

**Comment by mareknovotny** [comment]
just wrong target branch, sorry. Now fixed

**Review by yesamer — APPROVED** [review]

**Review by jomarko — APPROVED** [review]
No QE review done, will be manually tried once official product build arrives corresponding to 7.52.x branch.

**Comment by mareknovotny** [comment]
@jomarko yes, this is more about fixing 3 failing tests to not presume they are broken

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins retest this please

**Pull request merged**
