### PR TITLE
[AF-2151] Modify asset Save button behavior and presentation

### PR DESCRIPTION
**Pull request by gabriel376**
**[AF-2151](https://issues.jboss.org/browse/AF-2151) Modify asset Save button behavior and presentation**

Peek 2019-09-11 20-06

* Depends on https://github.com/kiegroup/appformer/pull/783
* Depends on https://github.com/kiegroup/kie-wb-common/pull/2849
* Depends on https://github.com/kiegroup/jbpm-designer/pull/864

### CODE REVIEW

**Comment by gitgabrio** [comment]
Hi @gabriel376 

I see that this PR is related to others on lower layers (kie-wb-common, appformer) and that it changes the behavior of the _Save_ button in *some* drools-wb editors, but not in others: did you by chance verified if _Save_ buttons in other editors have been somehow involved by all those changes? In particular, I'm referring to ScenarioSimulation, but of course the same may apply to other.
Many thanks!

**Comment by ederign** [comment]
please jenkins execute fulldownstream build

**Comment by ederign** [comment]
hi @gitgabrio we will update all the active business central editors, so you should expect that ScenarioSimulation toolbar save button will be updated. We are gathering all information here: https://issues.jboss.org/browse/AF-2151

**Comment by gitgabrio** [comment]
Hi @ederign, thanks!
Please remember that inside Scenario simulation there are two "Save" buttons (one is inside the "Settings" panel) and that we have done some small override to provide the expected behavior (if you are interested what and why, feel free to ping and I'll be glad to explain). 
Cheers

**Comment by porcelli** [comment]
@gitgabrio I'm not sure the origin of such "Save" action there, it's not a standard action, to say the least. I've learned that this button came from this JIRA and was based on UX proposal (https://issues.jboss.org/browse/DROOLS-3492).

So... I'd keep that button of settings as-is for now... and I'd like, when we have the time, to have a second review about this action in this particular place. My personal opinion on this is that we already have two places for general configurations:
 - Project: all projects have the "Settings" tab that we include all project-related settings in one place.
 - User: user-level configurations are available in general settings.
 - Installation: same for installation level configs.

@lclay2 ^

**Comment by gitgabrio** [comment]
Hi @porcelli that's the reason I proposed to talk of this.
I remember there was a reason I've implemented that, but surely it seems "redundant". Anyway, as you said, it would like too to talk a little bit of it before making any change.

**Comment by ederign** [comment]
OK, so meanwhile we will keep this button as is ok?

**Comment by porcelli** [comment]
+1 @ederign - keep as-is for now.

**Pull request merged**
