### PR TITLE
GUVNOR-3473: Add Pinned mode indicator

### PR DESCRIPTION
**Pull request by jomarko**
screenshot from 2017-09-07 23-04-39
screenshot from 2017-09-07 23-04-50
@manstis @karreiro please have a look.

### CODE REVIEW

**Comment by manstis** [comment]
How about using pushpin icon when pinned and nothing otherwise. We use the lock icon for when the file is locked (by another User).

**Comment by manstis** [comment]
I'll look more tomorrow but I am thinking to adjust the shown icon in the enter/exit pinned mode methods.. but it might be obvious to me tomorrow why you out it where you have!

**Comment by manstis** [comment]
I should add.. it looks ok on the whole :-)

**Comment by jomarko** [comment]
@manstis I had exactly this icon in mind, unfortunately I haven't found it in `org.gwtbootstrap3.client.ui.constants.IconType`, But sure I am open to any icon, also that in standard mode no icon is shown. Lets agree on the final solution in the morning.

**Comment by jomarko** [comment]
pinmode

@manstis Icon shown just in pinned mode, I used icon that was the most similar to pin I know from IDEA. Let me know if you are aware about better/nicer/more self explanatory icon. Thanks.

**Comment by manstis** [comment]
Nice improvement @jomarko 

Shame we can't get the icon we'd like.. I tried locally to no end :-(

**Comment by jomarko** [comment]
@karreiro sending reward to you right now. Thanks I will amend the commit.

**Pull request merged**
