### PR TITLE
DROOLS-6511: Create Reproducer for ConcurrentModification exception

### PR DESCRIPTION
**Pull request by jomarko**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[DROOLS-6511](https://issues.redhat.com/browse/DROOLS-6511)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* https://github.com/kiegroup/drools/pull/3743

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by jomarko** [comment]
Jenkins do fdb

**Review by Rikkola — APPROVED** [review]

**Review by jstastny-cz — APPROVED** [review]
LGTM.

**Review by mariofusco — APPROVED** [review]

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
Started builds once more as the drools part of the ensemble now contains simplified version of the fix.

**Comment by jomarko** [comment]
Failed test:
- org.kie.wb.test.rest.functional.ProjectIntegrationTest.testDeployProjectSnapshotTwice

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
Build failure caused by:
```
Caused by: java.net.UnknownHostException: bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com: Name or service not known
```

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge together with https://github.com/kiegroup/drools/pull/3743

**Pull request merged**
