### PR TITLE
[Drools-3341] Duplicate DO columns

### PR DESCRIPTION
**Pull request by yesamer**
https://issues.jboss.org/browse/DROOLS-3341

Dear @kkufova, I kindly ask you to start to test this new functionality

@gitgabrio @danielezonca @annabaker  please review it.

### CODE REVIEW

**Comment by kie-ci5** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kkufova** [comment]
@krisv, could you please add @yesamer to the KIE group?

**Comment by yesamer** [comment]
Please use https://github.com/kiegroup/drools-wb/pull/1106 which replace this PR.
No changes, only the branch of the sources is different.

**Comment by yesamer** [comment]
https://github.com/kiegroup/drools-wb/pull/1106

**Comment by mareknovotny** [comment]
@kkufova @krisv I invited @yesamer to join our org

**Comment by kkufova** [comment]
@mareknovotny, thank you!

**Pull request closed without merging**
