### PR TITLE
[7.59.x] DROOLS-6726 : Delete BRL column in model view return error (#1528)

### PR DESCRIPTION
**Pull request by Rikkola**
* DROOLS-6726 : Delete BRL column in model view return error

* Update drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/BRLConditionColumnSynchronizerTest.java

(cherry picked from commit c9576684643bcd97677da9991f8ae982e12d00e3)

[DROOLS-6726](https://issues.redhat.com/browse/DROOLS-6726)

[War here 21.1.2022](https://drive.google.com/file/d/1lVyNXOtr4Ugl16-f2aD9Z9jm349VNOkd/view?usp=sharing)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
@jomarko Ok ready for reviews, linked the war in the description.

**Comment by Rikkola** [comment]
`[2022-01-11T10:31:51.640Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.8.0:install-node-and-npm (install node and npm) on project appformer-js: Could not download Node.js: Could not download http://download.devel.redhat.com/rcm-guest/staging/rhba/dist/node/v12.16.2/node-v12.16.2-linux-x64.tar.gz`

Jenkins retest this

**Comment by Rikkola** [comment]
Jenkins run fdb

**Review by jomarko — APPROVED** [review]
Manualy tried scenario form jira. It works. Thank you.

**Review by RishiRajAnand — APPROVED** [review]

**Comment by Rikkola** [comment]
@kiegroup/gatekeepers Can I get a merge please.

**Pull request merged**
