### PR TITLE
[7.5.x] DROOLS-2160: Add spacing between table cells

### PR DESCRIPTION
**Pull request by jomarko**
This PR is corollary of Getting started experience requirement, where @ibek asked for more spaces between elements in scenario designer.

**Cherry-pick** of #770

### CODE REVIEW

**Comment by manstis** [comment]
@jomarko advised this is a cherry-pick...

@jomarko Do you think, in the future, you could state in the PR whether it's a cherry-pick?

**Comment by jomarko** [comment]
@manstis definitely I can, in this one I put short sentence "This is corollary of ...", but I admit, It can be easily overseen, please what do you think should be ideal to make clear and easily distinguishable which PRs are just cherry-picks?

**Comment by manstis** [comment]
@jomarko I saw your original comment about "corollary" however to me that simply means this PR is for the same reason as that with which it is correlated but not necessarily exactly the same code changes as those already reviewed and approved... Sometimes we do a fix for one branch that contains quite different code to the other depending on how the two branches may have diverged. In those cases we'd need to review and approve the different PRs individually although they may be for the same JIRA,

**Comment by jomarko** [comment]
@manstis lesson learned, I will use **cherry-pick** vs **corollary** more carefully, sorry for inconvenience.

**Comment by jomarko** [comment]
@manstis it can be merged I believe.

**Pull request merged**
