### PR TITLE
BXMSPROD-1435 - fix GWT compilation issues

### PR DESCRIPTION
**Pull request by almope**
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>

**Thank you for submitting this pull request**

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1435

### CODE REVIEW

**Comment by almope** [comment]
jenkins execute fdb

**Comment by almope** [comment]
jenkins execute fdb

**Comment by almope** [comment]
jenkins execute fdb

**Review by Ginxo — APPROVED** [review]
LGTM

**Review by jomarko — CHANGES_REQUESTED** [review]
I am sorry I can not approve this PR, because I am not able to reproduce the fail on latest main branch, thus I am not sure if changes here I needed. Could you please provide more details how to reproduce the issue to see it fails without this PR and pass with this PR?

What I tried with latest main branch was:
- `cd drools-wb/drools-wb-webapp; mvn clean package`
- `cd drools-wb/drools-wb-webapp; mvn -B -Dfull=true -Dmaven.test.failure.ignore=true -Drevapi.skip=true -Denforcer.skip=true -Dgwt.compiler.localWorkers=1 -Dproductized=true -DskipTests=true -Dfindbugs.skip=true -Dcheckstyle.skip=true -DnpmRegistryURL=http://indy.newcastle.svc.cluster.local/api/folo/track/$buildContentId/npm/remote/npmjs/ -DnodeDownloadRoot=http://rcm-guest.app.eng.bos.redhat.com/rcm-guest/staging/rhba/dist/node/ -DnpmDownloadRoot=http://rcm-guest.app.eng.bos.redhat.com/rcm-guest/staging/rhba/dist/npm/ -DyarnDownloadRoot=http://rcm-guest.app.eng.bos.redhat.com/rcm-guest/staging/rhba/dist/yarn/ package`

**Comment by mareknovotny** [comment]
the build breaks probably on file path again in different environments like reported. We are really playing here too much a game of catching the long paths in classpath. I would say is the deps are not needed and we can limit them it is good way. If the deps are needed, it is not.

**Comment by almope** [comment]
@jomarko hi! Sorry, my bad, I didn't add any details to this PR thinking that the issue was well known. Thanks for reviewing.

I'm closing this as we are moving the local repository to a shorter path to reduce the entries length in the GWT compilation classpath. Anyway the reason for the failure on the GWT compilation is due to a product temporary build. It replaces the `Final` bit in the artifacts product version milestone by a `temporary`. While is true that we have hundreds of artifacts produced in the build and included in the GWT compilation classpath with as little as a 4 characters addition it makes the compilation fails. I guess we, sooner or later, will have to go through a similar PR.

**Pull request closed without merging**
