### PR TITLE
[7.5.x] DROOLS-2218: Catch NPE in CDI tests cleanup

### PR DESCRIPTION
**Pull request by jomarko**
@manstis hi, this is **cherry-pick** of #794

### CODE REVIEW

**Comment by ederign** [comment]
@jomarko 7.5.x is locked down currently for blockers only. This isn't a blocker right?

**Comment by jomarko** [comment]
@ederign same comment as in https://github.com/kiegroup/appformer/pull/155, if you think this should be closed, please let me know.

**Comment by jomarko** [comment]
@manstis so not sure, I was told 7.5.x is blockers only, should I close this PR?

**Comment by manstis** [comment]
@jomarko Let's see what @etirelli says on the other PR.

**Comment by etirelli** [comment]
Tests can be merged, no worries.

**Pull request merged**
