### PR TITLE
[7.18.x] DROOLS-1797 : Incorrect V&V results when operator is filled in the row 

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-1797
@jomarko @manstis My changes with @jomarko's tests. I could use a review here please.

Bundle:
https://github.com/kiegroup/drools-wb/pull/1107
https://github.com/kiegroup/drools/pull/2292

### CODE REVIEW

**Comment by jomarko** [comment]
@Rikkola please mention other part of the ensmeble in the PR description

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
@Rikkola Looks like we need the ACKs on https://issues.jboss.org/browse/RHDM-711 before merge.

**Comment by manstis** [comment]
@Rikkola ...and if I log into JIRA I see they're there!

**Pull request merged**
