### PR TITLE
[7.3.x] GUVNOR-3524: Do not expose unsupported features by UI (e.g. scorecards, decision trees)

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-3524

This is the corollary of https://github.com/kiegroup/drools-wb/pull/641 for 7.3.x 

(cherry picked from commit a0ad062eec89944965b6340dc4c9351bfd5fe2a0)

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
