### PR TITLE
RHBA-520: Cover validation of huge spreadsheet table

### PR DESCRIPTION
**Pull request by jomarko**
@Rikkola @manstis please have a look.

### CODE REVIEW

**Comment by manstis** [comment]
@jomarko Given https://issues.jboss.org/browse/RHBA-520 do you want this merged? 

Doesn't it run the risk of OOM'ing Jenkins?

**Comment by jomarko** [comment]
OOM occurs during indexing, validation should be fine, we can run tests here (10 times lets say) and check if OOM occurs. WDYT?

**Comment by manstis** [comment]
@jomarko No, if this build is green then I am OK with merging as it is.

**Comment by jomarko** [comment]
@manstis hehe, you was right: `Caused by: java.lang.OutOfMemoryError: Java heap space`, so rpobably this can't be merged.

**Pull request closed without merging**
