### PR TITLE
GUVNOR-3103: Prevent pattern binding from using spaces

### PR DESCRIPTION
**Pull request by jomarko**
screenshot from 2017-05-22 16-50-17
screenshot from 2017-05-22 16-50-08
screenshot from 2017-05-22 16-49-21

### CODE REVIEW

**Comment by jomarko** [comment]
@karreiro could I ask you again for the review?

**Comment by jomarko** [comment]
@manstis It makes sense to reuse, applying right now. Thanks.

**Comment by jomarko** [comment]
@manstis have a look please, I found some duplication of `BindingTextBox`. Let me know if you have idea of other place where it could be possibly used.

**Comment by jomarko** [comment]
@manstis, I had in mind the same idea "some shared place". But to be honest, I was lazy to find some. However, the one you have proposed seems pretty reasonable. I will amend the PR.

**Comment by jomarko** [comment]
Updated. Now dependent on https://github.com/kiegroup/kie-wb-common/pull/895

**Comment by manstis** [comment]
@jomarko Looks like you missed an occurrence of the old class?

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
@manstis test passes now.

**Pull request merged**
