### PR TITLE
AF-1933: AssetQueryService takes some time before return last created assets

### PR DESCRIPTION
**Pull request by jesuino**

### CODE REVIEW

**Comment by ederign** [comment]
@domhanak can you please assign this to the most suited qe?

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
I will do PR review for QE department.

**Comment by danielezonca** [comment]
@domhanak 
Do you want to test this too or can we merge?

**Pull request merged**
