### PR TITLE
jboss-servlet-api_4.0_spec dependency added

### PR DESCRIPTION
**Pull request by Ginxo**
due to https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/PROD/job/nightly/job/master/85 error

### CODE REVIEW

**Comment by Ginxo** [comment]
jenkins execute full downstream production build

**Comment by Ginxo** [comment]
please @yesamer @karreiro @jomarko please assign reviewers

**Comment by Ginxo** [comment]
@jomarko should we keep `org.jboss.spec.javax.servlet:jboss-servlet-api_3.1_spec` then?

**Comment by jomarko** [comment]
Ok, build si failing, so I guess will be not so easy, looking again.

**Comment by yesamer** [comment]
@Ginxo @jomarko  Hi guys! In my opinion a version for that dependency is currently missing: if you see here in our kie-parent pom https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/pom.xml#L216, the version for `org.jboss.spec.javax.servlet.jboss-servlet-api_3.1_spec` is set, where is not available for `org.jboss.spec.javax.servlet.jboss-servlet-api_4.0_spec`

**Comment by yesamer** [comment]
@Ginxo @jomarko In addition, I'm not sure we can have both servlet 3.1 and servlet 4.0 version managed together. Our target application server is Wildfly 18, which is certified with servlet 4.0 version. Considering this, probably the best solution should be to replace 3.1 version with 4.0 version, but I don't have an idea on the potential impact in our codebase. @mareknovotny WDYT? Can you please give us any hints?

**Comment by jomarko** [comment]
@Ginxo @yesamer see my PR https://github.com/kiegroup/appformer/pull/975 there I am ensuring just one version on jboss-servlet-api. It helped me locally to fix build of drools-wb-dtable-xls. However yes it is question if we wont 3.1 or 4.0

**Comment by mareknovotny** [comment]
@Ginxo please exclude that dependecy instead of declaring it

**Comment by Ginxo** [comment]
solved by https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1235

**Pull request closed without merging**
