### PR TITLE
[7.6.x] DROOLS-2371: Unable to complete your request. The following exception occurred: (TypeError) in Guided Decision Table Graph

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-2371

This is the corollary of https://github.com/kiegroup/drools-wb/pull/824 for 7.6.x.

(cherry picked from commit 52edf69c27de519d1fff9465f10461d5533f8c06)

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
@jomarko I'm guessing we don't have CI jobs for 7.6.x.

@mbiarnes ^^ Is this true?

**Comment by jomarko** [comment]
@manstis I tried to build locally but getting error messages about not existing bom artifacts in the version 7.6.1.

**Comment by manstis** [comment]
@jomarko Thanks.. blame it on @etirelli ;-)

**Comment by etirelli** [comment]
Hey, I am trying to save you guys from doing more work! :)

**Pull request merged**
