### PR TITLE
DROOLS-5804: Column rule name be increased 

### PR DESCRIPTION
**Pull request by yesamer**
**JIRA**: https://issues.redhat.com/browse/DROOLS-5804

Just a style update on Coverage Report, as required in related ticket.
I overridden the `width` value considering it's not possible to modify the original style property.

Screenshot from 2020-11-09 15-42-48

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by jstastny-cz** [comment]
jenkins do fdb

**Review by Rikkola — APPROVED** [review]
Looks like it works in Chrome and Edge.

**Comment by jstastny-cz** [comment]
LGTM

**Comment by yesamer** [comment]
@jstastny-cz is it approved?

**Review by jstastny-cz — APPROVED** [review]

**Pull request merged**
