### PR TITLE
DROOLS-2106: Run rules with attributes in test scenario

### PR DESCRIPTION
**Pull request by jomarko**
Dependent on #702

### CODE REVIEW

**Comment by manstis** [comment]
I'll guess this will have a merge conflict when #702 is merged; so will defer my review.

**Comment by jomarko** [comment]
@manstis sure, no problem.

**Comment by jomarko** [comment]
@manstis ready for merge. Just reminder.

**Comment by manstis** [comment]
@Rikkola Fancy a look too (if you'd prefer not to see them - as you're busy elsewhere - just say.. I'm just letting you look by default since these PRs touch on Test Scenario testing).

**Comment by Rikkola** [comment]
@manstis No worries. These are quick to check and good to know what is happening in drools-wb.

**Pull request merged**
