### PR TITLE
[7.14.x] RHPAM-1722 : NoClassDefFoundError warnings when starting Workbench

### PR DESCRIPTION
**Pull request by Rikkola**
(cherry picked from commit 388799ba11c18314571032bb3636f7ac7518c6ea)

https://issues.jboss.org/browse/JBPM-7869
https://issues.jboss.org/browse/RHPAM-1722

@jomarko @manstis The same fix for 7.14.x cherry-picked no conflicts. If you could please review.

### CODE REVIEW

**Comment by Rikkola** [comment]
One thousand! What do I win?

**Comment by manstis** [comment]
@Rikkola You'll need a RHPAM/RHDM JIRA with the necessary ACKs for this to be merged...

**Comment by Rikkola** [comment]
Thought it had one. Looks like it was just targeting community.

**Comment by manstis** [comment]
@Rikkola I could not see one linked from the community JIRA nor does this PR reference it..

If one does already exist please can you update the PR title and commit message?

**Comment by jomarko** [comment]
@Rikkola Hi, I built this PR and consequently `kie-wb-distributions` using `-Dfull`, however in the obtained wars, I am getting [1] in the runtime.

[1]
13:20:19,839 ERROR [org.kie.workbench.common.services.verifier.service.VerifierWebWorkerServlet] (default task-6) Failed to load verifier web worker.

**Comment by Rikkola** [comment]
@manstis acks, tickets and commit updated.

**Comment by Rikkola** [comment]
@manstis good evening. Acks in and reviews, if you could please merge.

**Comment by Rikkola** [comment]
@manstis I see the build is still not done. Waiting.

**Comment by Rikkola** [comment]
I only changed the commit comment text, but best to be safe.

**Comment by Rikkola** [comment]
@manstis now it is green and ready.

**Pull request merged**
