### PR TITLE
GUVNOR-3036: Detect missing imports during wid validation

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by jomarko** [comment]
@manstis please take a look when you have a moment. Changes are in class you coded at most.

**Comment by jomarko** [comment]
@manstis thanks for merging, please, let me know if I should cherry pick into 7.0.x.

**Comment by manstis** [comment]
Hi @jomarko @etirelli opinion is to only merge to 7.0.x now if it's critical... IDK.. your decision!

**Comment by jomarko** [comment]
@manstis ok, then I am fine with keeping this just i master

**Pull request merged**
