### PR TITLE
GUVNOR-2782 fix conflict after merge

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by manstis** [comment]
@jomarko @Rikkola Oh dear.. looks like something is royally broken :-(

**Comment by jomarko** [comment]
Sorry guys, I pushed another try. Today is not my day.

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
@manstis @Rikkola it is green now.

**Comment by manstis** [comment]
Thanks @jomarko

**Pull request merged**
