### PR TITLE
DROOLS-4461: Show date picker for LocalDate

### PR DESCRIPTION
**Pull request by jomarko**
Ensemble together with:
- https://github.com/kiegroup/drools/pull/3064
- https://github.com/kiegroup/kie-wb-common/pull/3322
- https://github.com/kiegroup/kie-docs/pull/2786

For more details see https://issues.redhat.com/browse/DROOLS-4461

### CODE REVIEW

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by Rikkola** [comment]
The test coverage is quite low I'm not sure if there are reasonable easy picks to get it better. The duplication I don't think is that big of an issue here, but it might be possible to use shared base for the different date types. Still approving I leave it up to you to see what is best given the time you have.

**Comment by karreiro** [comment]
Jenkins do full downstream build.

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by yesamer** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by jstastny-cz** [comment]
@jomarko 
1. the widget is supposed to be displayed only on the grid? It's not presented when setting a default value in guided decision tables when using the wizard:
Screenshot from 2020-08-17 17-17-54

2.There's a weird behavior when closing the widget by clicking "elsewhere". When the widget is presented, just click on an empty space outside of it (to loose focus) - the value in the field is subtracted by 2 days?

3. When removing the previously added value - there seems to be no clear way to confirm an empty cell value to be saved - the only option is to cancel editing mode navigate to the cell and pres Delete key.

4. When removed the previously added value and clicked elsewhere in the grid the following unexpected error is presented: "Uncaught exception: Exception caught: Exception caught: (TypeError) : Cannot read property 'getTimezoneOffset_0_g$' of null Caused by: Exception caught: (TypeError) : Cannot read property 'getTimezoneOffset_0_g$' of null Caused by: (TypeError) : Cannot read property 'getTimezoneOffset_0_g$' of null"

I'll try FDB to rule out any issues in my build.

**Comment by jstastny-cz** [comment]
Jenkins start fdb

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
Jenkins please retest this

**Review by Rikkola — CHANGES_REQUESTED** [review]
So there actually is an issue. I made a regular Condition for GDST and did not fill the default value. When I go back and edit the default value a the "Value options" tab gives an exception.

**Comment by jomarko** [comment]
Opened more than half a year. Closing without a replacement.

**Pull request closed without merging**
