### PR TITLE
[7.5.x] DROOLS-2263: Unexpected results in GDST when using enumerations with commas - info

### PR DESCRIPTION
**Pull request by Rikkola**
(cherry picked from commit f68c96ca7432a3787f9dadb9387f109bdc8227ea)

https://issues.jboss.org/browse/DROOLS-2263

And the same for 7.5.x

### CODE REVIEW

**Comment by Rikkola** [comment]
@barboras7 Something you might want to check.

**Comment by Rikkola** [comment]
@manstis @jomarko You approved the original change to master. This is the same 1:1. Reviewes are welcomed.

**Comment by manstis** [comment]
@Rikkola I assume this can be merge? Could you however please confirm.

**Comment by Rikkola** [comment]
@manstis It is ok.

**Pull request merged**
