### PR TITLE
DROOLS-6477: Collections Data Objects can be filled with expressions only.

### PR DESCRIPTION
**Pull request by yesamer**
**JIRA**: https://issues.redhat.com/browse/DROOLS-6477

**referenced Pull Requests**: 
* https://github.com/kiegroup/drools/pull/3725

The issue occurs when the user imports a Collection or a Map from the "Data Object" tab.
Screencast from 07-08-2021 10_35_28 AM

In the  Test Tools area, the Collection (eg. ArrayList) will wrongly show `empty` as a field. Selecting it or the `ArrayList`fact, will not enable the Guided Collection Editor as expected. 

With the change introduced with this PR, now `value` field will be shown. As a results, adding the value parameter in the grid, will  show the Guided Collection Editor.

Screencast from 07-08-2021 10_34_29 AM

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
war file generated, downloading

**Review by karreiro — APPROVED** [review]
Thank you, @yesamer.

**Review by jomarko — COMMENTED** [review]
I found these two issues, for case, when user added some collections via Data Objects tab. I should still verify case when fields of Facts used in Rules are collections. However I am postponing that check, as not sure if you will address issues found until now as part of this PR or separately.

### 01
TreeMap is value[boolean], not value[TreeMap]
Screenshot from 2021-07-12 11-32-50


### 02
If just the instance is set, then the `expression` property can't be never changed to `value`
Screenshot from 2021-07-12 11-33-12

Screenshot from 2021-07-12 11-33-20

In the second picture, if you click OK, nothing happens.

**Comment by yesamer** [comment]
@jomarko Thank you for reviewing it. 
1) It's fixed, I forgot to add `TreeMap` in the supported collections list
2) I'll manage in another ticket. The issue occurs switching from a Simple value (eg. `ArrayList`, 'Integer`, ...) to an Expression type and vice-versa.

**Comment by yesamer** [comment]
Jenkins do fdb

**Comment by yesamer** [comment]
Jenkins do fdb

**Comment by yesamer** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
jenkins not available, need to postpone review as need to work with kie-wb-distributions/business-central-parent/business-central-webapp

**Comment by yesamer** [comment]
@jomarko I can provide you the war I generated in my local, to solve the problem with jenkins.

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by yesamer** [comment]
Jenkins do fdb

**Review by jomarko — APPROVED** [review]
Thank you @yesamer

**Comment by jomarko** [comment]
Please do not forget to merge https://github.com/kiegroup/kie-docs/pull/3761 together with this ensemble.

**Pull request merged**
