### PR TITLE
DROOLS-6838 : XLS decision tables should respect the .properties files sheets definition

### PR DESCRIPTION
**Pull request by Rikkola**
[DROOLS-6838](https://issues.redhat.com/browse/DROOLS-6838)
[The war](https://drive.google.com/file/d/1Psr4EWYxPZ1xHpqm_5ucD9BE-R3cjyzi/view?usp=sharing)
<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
@jomarko I'll make a war for you
And clean up the e.printStackTrace();

**Comment by Rikkola** [comment]
@jomarko I'll make a war for you
And clean up the e.printStackTrace();

**Comment by Rikkola** [comment]
@jomarko I'll make a war for you

**Comment by Rikkola** [comment]
@jomarko I'll make a war for you
And clean up the e.printStackTrace();

**Comment by Rikkola** [comment]
@jomarko I'll make a war for you
And clean up the e.printStackTrace();

**Comment by Rikkola** [comment]
@jomarko Ok ready.

**Review by jomarko — CHANGES_REQUESTED** [review]
@Rikkola thank you for a PR. The tests seems to proving the feature works. However I am not able to use the new feature manually. I miss some documentation. Could you please provide a manual how to use new feature? Probably we should provide such maual into kiegroup/kie-docs?
- What should be the properties filename
- What should be the properties file content
- What should be the order of importing assets into business central? (xls first or properties first)
- The PR adds some "beans.xml" into test resources, is such file needed for this new feature to get it working?

**Comment by Rikkola** [comment]
@jomarko This was actually an unknown feature, but ran into it when looking into why this did not work. By default only the first page from XLS is used for dtables. With a `originalname.xml.properties` it is possible to select the pages that are used from the XLS file. This is mentioned in a note at the bottom of this https://docs.drools.org/7.66.0.Final/drools-docs/html_single/index.html#decision-tables-defining-proc. Order of importing should not matter, I added the XLS first myself.

**Comment by Rikkola** [comment]
@jomarko Ok updated. beans.xml was not needed.

**Comment by jomarko** [comment]
@Rikkola thank you, I am able to see decision table source generated for all tabs. Probably I was mis-using it somehow previously.

However I see these two problems:
### package and imports
`package` and `imports` are duplicated in generated source
Screenshot from 2022-03-09 11-54-51

### testing
I am not able to test the xls nor old test scenario or new scenario simulation
Screenshot from 2022-03-09 11-54-37
Screenshot from 2022-03-09 11-54-23

**Review by jomarko — APPROVED** [review]
In my last review `insert($r)` statement was missing. After recheck. I can confirm the code works.

@Rikkola thank you for an explanation and PR itself.

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by Rikkola** [comment]
Jenkins retest this

**Review by yesamer — APPROVED** [review]
LGTM, Thank you @Rikkola

**Pull request merged**
