### PR TITLE
DROOLS-5230: Managing a List of structures in Test Scenario editor produces an Exception

### PR DESCRIPTION
**Pull request by yesamer**
The issue occurs when a "user defined" java class is used as type parameter of a List eg. `List<Clazz>` and that class contains a field which is a "user defined" java class as well. Screenshot show an example:

Screenshot from 2021-01-20 10-02-49

Author
+ books (List<Book>)
   . isAvailable (boolean)
   . name (string) 
   . ....
   + **author (Author)**    _<----  Issue occurs with this nested class field_
       . name
       . ...

With current version there are several issues:
- Not possible to correctly delete / modify a list item 
- the nested **author (Author)** reference is THE SAME for all items (eg. try to create multiple items of the list. If you try to change a field of Author, this will be propagated to all items!)

**JIRA**: https://issues.redhat.com/browse/DROOLS-5230

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
jenkins run fdb

**Review by Rikkola — APPROVED** [review]

**Comment by jstastny-cz** [comment]
I have `Library -> books:List<Book>` and `Book->author:Person` getting unexpected error when inserted fact Library.books and using Collection editor adding into the input field for Person->name.

error details:
```
Uncaught exception: Exception caught: (TypeError) : Cannot read property 'Vc' of undefined Caused by: (TypeError) : Cannot read property 'Vc' of undefined
```

Screenshot from 2021-01-26 16-06-26

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
@jstastny-cz Thank you for reporting. I fixed the wrong behavior.

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by jstastny-cz** [comment]
I've been able to test with the artifacts from the FDB - the build failed, but the artifacts were there (probably failed at later stage). Not blocked by the failure in testing.

**Comment by yesamer** [comment]
@jstastny-cz Ok, I launched it again because I merged the PR with master (now with version `7.50`). But you can test with previously generated artifacts.

**Comment by jstastny-cz** [comment]
I just want to clarify one thing, consider following case (ignoring some unimportant things in the domain):
```
public class Library {
    private List<Book> books;
}
public class Book {
    private String title;
    private Author author;
}
public class Author {
    private String name;
    private Classification classification;
}
public class Classification {
    private String era;
}
```
i.e. adding one more level to the depth of custom object navigation.
Screenshot from 2021-01-28 17-17-35


I can't fill in Classification for the Author then, the field is not there - is it because we support just limited level of recursion now?

So I would like to insert fact Library->books. I would expect I would add Book instances. I can see author field there, it has all fields shown as input fields BUT the field `classification`.

**Comment by yesamer** [comment]
@jstastny-cz Yes, these are two known limitation of Collection Editor. 

1. For the first limitation, when we created the Collection Editor we decided to support only 1 level of nesting object. This is because it's wasn't easy to manage a potential `n` levels of nesting inside a popup. A ticket which track the intention to analyze this limitation and found a better solution in order to remove this limitation is https://issues.redhat.com/browse/DROOLS-4290;
2. About this, basically we don't support nested collection. My intention is to implement it with https://issues.redhat.com/browse/BAPL-1841.

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
jenkins run fdb

**Review by jstastny-cz — APPROVED** [review]
LGTM, thanks

**Pull request merged**
