### PR TITLE
JBPM-6511: Remove the Business Dashboards entry from mega menu

### PR DESCRIPTION
**Pull request by dgutierr**
Changes required by kiegroup/kie-wb-distributions#653

@manstis @jhrcek Can you review it as well? Thanks!

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by jhrcek** [comment]
@dgutierr sorry for the late reply, I was on PTO. The build is failing because of checkstyle violations (using start import). Could you please fix that (and maybe use predefined [IntelliJ formatter](https://github.com/kiegroup/droolsjbpm-build-bootstrap/tree/master/ide-configuration/intellij-configuration/code-style) to prevent this kind of failure in the future)?

**Comment by dgutierr** [comment]
@jhrcek Done. Thanks for the hint.

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by dgutierr** [comment]
@manstis There are two test failures in the full build which I think are not related to this PR. Can you please confirm and merge if so? Thanx!

**Comment by manstis** [comment]
As @dgutierr points out the failing tests will not be caused by changed to ```drools-wb``` ```HomeProducer``` (as this class is not used by the end distributions used by tests). Merging.

**Pull request merged**
