### PR TITLE
[7.7.x] DROOLS-2593 : [Guided Decision Table] Trouble to add a row into table with WI

### PR DESCRIPTION
**Pull request by Rikkola**
(cherry picked from commit 68ffe850dc01fce6af8bb68e11e13765b74e4621)

https://issues.jboss.org/browse/DROOLS-2593

### CODE REVIEW

**Comment by Rikkola** [comment]
@jomarko @barboras7 One for the 7.7.x that could use a review please.

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
Artifacts generated and available for manual testing.

**Comment by Rikkola** [comment]
@jomarko Thank you

**Comment by Rikkola** [comment]
jenkins execute full downstream build

**Comment by Rikkola** [comment]
jenkins execute full downstream build

**Comment by Rikkola** [comment]
jenkins execute full downstream build

**Comment by Rikkola** [comment]
kie-wb-tests-rest fails to set up the wildfly container.

jenkins execute full downstream build

**Comment by Rikkola** [comment]
Still the same issue, but also had the error in another 7.7.x PR so tempted to think it goes away if I do...

jenkins execute full downstream build!

**Comment by jomarko** [comment]
@Rikkola I think now RHDM-323 and RHPAM-666 should be marked as resolved

**Comment by mareknovotny** [comment]
@jomarko, @Rikkola  where is RHDM-323 merged? I can't see that cherry-picked or PR for 7.5.x branch

**Comment by jomarko** [comment]
@mareknovotny rhdm-323 has target release rhdm-7.1.0 GA, thus I believe no need to cherry-pick into 7.5.x

**Comment by mareknovotny** [comment]
@jomarko the thing is that RHDM-323 is now resolved, but not really resolved on branch 7.5.x so that is the issue we will miss it for RHDM when we do next CP. So right now we need to go back with RHDM-323 to reopen it and wait for cherry-pick or PR.

**Comment by jomarko** [comment]
@mareknovotny I am fine if we decide to cherry-pick to 7.5.x, however I still think we are in valid situation. We have fix for an issue on master, however we don't want to risk break something on maintenance branch  7.5.x so we targeted the issue to 7.1.0 not for 7.0.x.

Summary, if you think the RHDM Resolved status is equivalence for PR merged fix in 7.5.x I am fine with that and in that case please update the jira status and target release appropriately.

**Comment by mareknovotny** [comment]
@jomarko yep, I know that we very probably will have 7.1.0 based on some new branch, but for now it is safe to say that is unknown.

**Pull request merged**
