### PR TITLE
[DROOLS-3568] Reset new scenario popup status. Fixed tests

### PR DESCRIPTION
**Pull request by gitgabrio**
@kkufova @danielezonca 

See https://issues.jboss.org/browse/DROOLS-3568

### CODE REVIEW

**Comment by gitgabrio** [comment]
@kkufova 
Should be fixed now.

**Comment by kkufova** [comment]
@gitgabrio, agreed. The warning text could be:

> Choose a valid DMN asset from the list.

**Comment by gitgabrio** [comment]
@kkufova
Should be fixed now.

**Comment by gitgabrio** [comment]
jenkins please retest this

**Comment by gitgabrio** [comment]
@manstis 
Hi. Could you please merge this, squashing commits? Thanks.

**Pull request merged**
