### PR TITLE
[DROOLS-3008] It should not be possible to delete the GIVEN/EXPECTED header from a Test Scenario (Preview) table

### PR DESCRIPTION
**Pull request by gitgabrio**
@kkufova @danielezonca @Rikkola 
Scope of this PR is to fix column deletion policy:
1) column deletion should be allowed only for GIVEN/EXPECTED columns
2) when deleting the last GIVEN/EXPECTED column, a new autogenerated one should be put in place, so that there will always be at least one GIVEN/EXPECTED column

### CODE REVIEW

**Comment by Rikkola** [comment]
Good day. Is there a test for item number 2?

**Comment by gitgabrio** [comment]
@Rikkola 
Add that test with last commit

**Comment by gitgabrio** [comment]
@kkufova 
Fixed "deselection" and pom

**Comment by gitgabrio** [comment]
@manstis 
Could you merge this, please?

**Comment by gitgabrio** [comment]
@manstis 
please hold on this merge

**Comment by gitgabrio** [comment]
@manstis
Could you merge this, please?

**Pull request merged**
