### PR TITLE
JBPM-8955 defaultHandler tag is missing from new WID files

### PR DESCRIPTION
**Pull request by bxf12315**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
@xiezhang7 should we also add a default Handler to template for new WID? And button as well for easier addition for manual typing WID?

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @bxf12315,

according to steps to reproduce, the content of the newly created WID file should already contain "defaultHandler", but when I created new WID file I can't see it in the file content [1].

Button for the Default Handler works good.

So, @bxf12315 I am not sure are steps to reproduce too strict (no need in defaultHandler in newly generated WID) or it is PR not completed? 

[1]
image

**Comment by bxf12315** [comment]
> Hi @bxf12315,
> 
> according to steps to reproduce, the content of the newly created WID file should already contain "defaultHandler", but when I created new WID file I can't see it in the file content [1].
> 
> Button for the Default Handler works good.
> 
> So, @bxf12315 I am not sure are steps to reproduce too strict (no need in defaultHandler in newly generated WID) or it is PR not completed?
> 
> [1]
> image

https://issues.redhat.com/browse/RHPAM-2411,The issue do not mention it. Is it necessary?

**Comment by hasys** [comment]
@bxf12315, yea, actually there are no Actual and Expected result at all so it's hard to say what is expected. But in steps to reproduce I can see step 5:
> Observe text of **resulting WID file** as well as palette in the WID editor

So, from this step 5 follows that defaultHandler should present in resulting WID file AND on the palette as well.

Let's ask reporter about what is it really mean. Thank you!

**Comment by hasys** [comment]
Hi @bxf12315 after consultation with Jira issue author all looks good to me now. Thank you!

### Check list
- [x] ACKs are set
- [x] Affected version is set property
- [x] Is realization aligned to jira description?
- [x] Both Jenkins jobs are green

### Code review
- [x] Code coverage
- [x] License headers
- [x] Static analyser gates
- [x] Code Style

### Acceptance Criteria
> See Steps to Reproduce in jira issue

- [x] Tested with full downstream build

### Found issues
* None

**Comment by jstastny-cz** [comment]
Thanks @hasys for the complex review.

**Pull request merged**
