### PR TITLE
DROOLS-5171 Remove unused dependencies

### PR DESCRIPTION
**Pull request by jomarko**
For more details see https://issues.redhat.com/browse/DROOLS-5171

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
@dupliaka , thank you for feedback. This time I was not using any `mvn` command just my knowledge about `kiegroup` code base. `dashbuilder` was pretty suspicious for me and just tried to remove it. I can definitely have a look on dependencies you mention also. Just question what maven command do you use, I use `mvn dependency:analyze` that doesn't give always 100% correct results.

**Comment by dupliaka** [comment]
> @dupliaka , thank you for feedback. This time I was not using any `mvn` command just my knowledge about `kiegroup` code base. `dashbuilder` was pretty suspicious for me and just tried to remove it. I can definitely have a look on dependencies you mention also. Just question what maven command do you use, I use `mvn dependency:analyze` that doesn't give always 100% correct results.

Well you can use dependency:tree to figure out is that is not used by any of the component
Plus from my knowlage dependency:analyze is not capable to take in account only runtime dependencies.

**Comment by jomarko** [comment]
@dupliaka I reported task for me to investigate those two you mentioned https://issues.redhat.com/browse/DROOLS-5185

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge

**Pull request merged**
