### PR TITLE
DROOLS-3398:

### PR DESCRIPTION
**Pull request by annabaker**
-Remove enable/disable methods from ListGroupItemView/ListGroupItemViewImpl
-Cleanup of ScenarioConfirmationPopupViewTest
-Refactor Append/PrependColumnCommand execution logic to new abstract AbstractInsertColumnCommand class

@danielezonca @gitgabrio @kkufova

### CODE REVIEW

**Comment by kkufova** [comment]
@annabaker, could you please rebase this PR on `master`? There is a conflict.

**Comment by annabaker** [comment]
@kkufova from my end i'm seeing "This branch has no conflicts with the base branch" -- i don't see the conflict.

**Comment by annabaker** [comment]
@manstis can you please squash and merge?

**Comment by annabaker** [comment]
@manstis can you please squash/merge?

**Pull request merged**
