### PR TITLE
[6.5.x] RHBPMS-5096: Cover validation of table with predicate calculation type

### PR DESCRIPTION
**Pull request by jomarko**
@manstis could you please have a look?

### CODE REVIEW

**Comment by manstis** [comment]
@mareknovotny Hi Marek, what's the status of the 6.5.x branch? 

Should I delay merging this until 6.4.9 is released? Thanks.

**Comment by mareknovotny** [comment]
@manstis this is wanted to be in 6.4.9, so if you are ok/approve this, merge please ASAP ;)

**Comment by manstis** [comment]
@mareknovotny Done.

**Comment by mareknovotny** [comment]
thanks @manstis

**Pull request merged**
