### PR TITLE
[7.0.x] GUVNOR-2998: GDT Editor - New column (wizard) - Error on 'Set the value of a field' plugin

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-2998

This is the corollary of https://github.com/kiegroup/drools-wb/pull/453 for 7.0.x

(cherry picked from commit e8d6a3186c2ab707dcdb19df4444505a1eb3ffb3)

### CODE REVIEW

**Comment by manstis** [comment]
@etirelli FYI..

**Comment by karreiro** [comment]
Thanks @manstis and @etirelli

**Comment by manstis** [comment]
@etirelli Can you please approve (and merge)

**Comment by manstis** [comment]
Thanks @karreiro .. shouldn't you be in bed!?

**Comment by karreiro** [comment]
¯\_(ツ)_/¯

**Comment by karreiro** [comment]
Precisely ;-D

**Pull request merged**
