### PR TITLE
KOGITO-4190: SceSim runner does not display reason for failure

### PR DESCRIPTION
**Pull request by yesamer**
**JIRA**: https://issues.redhat.com/browse/KOGITO-4190

(This PR contains only Tests updates required by changes in server-side) 

Aim of the change is to improve provided information to the user when test scenario is lanched from a cli with `maven test` command.
In case of a wrong assertion, currently the cli shows:
Screenshot from 2021-03-08 11-34-50
As a result of the proposed changes:
Screenshot from 2021-03-04 11-56-04
In details:
- Failing scenario are now marked as FAILURE and no more as ERROR;
- The text of the exception now contains the failure and changed in this way:
BEFORE
`#1: Scenario 'First Case' failed(/home/yamer/IdeaProjects/kogito-examples/dmn-pmml-quarkus-example/target/test-classes/KiePMMLRegressionTest.scesim)`
AFTER
`#1 First Case: Failed in "FactName.property": The expected value is "4" but the actual one is "3"(KiePMMLRegressionTest)`

This change affects Java Test Report, if test is launched in VSCode with "Debugger for Java Extension" Vs code plugin

BEFORE
zz

AFTER
Screenshot from 2021-03-04 11-50-37

**referenced Pull Requests**:

* https://github.com/kiegroup/drools/pull/3422
* https://github.com/kiegroup/drools-wb/pull/1470

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by Rikkola — APPROVED** [review]
All good.

**Review by jstastny-cz — APPROVED** [review]

**Comment by jstastny-cz** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
jenkins run fdb

**Comment by yesamer** [comment]
jenkins run fdb

**Pull request merged**
