### PR TITLE
GUVNOR-3198: [Guided Decision Table] Visual indication where the current view of Decision Table is located

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/GUVNOR-3198

Demo

---

Part of an ensemble:
- https://github.com/AppFormer/uberfire/pull/808
- https://github.com/kiegroup/drools-wb/pull/583
- https://github.com/kiegroup/kie-wb-common/pull/1110

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by karreiro** [comment]
Jenkins please execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

(Asking nicely may make it succeed!!)

**Comment by manstis** [comment]
Although having said that the failures appear to be those @mbiarnes has emailed BSIG about and hence I suspect unlikely to pass by simply repeating the full build request.. AFAIK @paulovmr is looking into the Selenium related failures. IDK if anyone picked up the REST related ones (or whether @cristianonicolai reported "fix" is related).

**Comment by karreiro** [comment]
Jenkins please execute full downstream build.

**Pull request merged**
