### PR TITLE
DROOLS-4863: Doughnut chart tooltip doesn't show correctly at Coverage Report panel 

### PR DESCRIPTION
**Pull request by yesamer**
This PR modifies Doughnut chart tooltip in order to be fixed (sticky), avoiding the reported issue (see JIRA)

Screenshot from 2021-04-21 16-46-08
Screenshot from 2021-04-21 16-48-42

**JIRA**: https://issues.redhat.com/browse/DROOLS-4863
[link](https://drive.google.com/file/d/1t5VfpXcUdJsqun465OMF3tMErjY582Rr/view?usp=sharing)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by yesamer** [comment]
Jenkins run fdb

**Comment by yesamer** [comment]
Jenkins run fdb

**Review by vpellegrino — APPROVED** [review]
Solution seems good and code as simple as possible.
Thanks @yesamer

**Review by karreiro — APPROVED** [review]
Thank you, @yesamer.

**Pull request merged**
