### PR TITLE
GUVNOR-3333, GUVNOR-3330: [Guided Decision Table] Edit condition column / Pattern change in condition column

### PR DESCRIPTION
**Pull request by karreiro**
See:
- https://issues.jboss.org/browse/GUVNOR-3330
- https://issues.jboss.org/browse/GUVNOR-3333

---

### GUVNOR-3330

Before:
3330-before

After:
3330-after

---

### GUVNOR-3333

Before:
3333-before

After:
3333-after

### CODE REVIEW

**Comment by karreiro** [comment]
@manstis @jomarko Could you please take a look? :-)

**Comment by karreiro** [comment]
ok to test

**Comment by manstis** [comment]
Jenkins please execute full downstream build dear chap.

**Comment by manstis** [comment]
@jomarko Can you discussion with @karreiro be taken _offline_; out of this PR?

I'd like to be able to merge the 7.2.x [corollary](https://github.com/kiegroup/drools-wb/pull/569) but it'd need your approval.

**Pull request merged**
