### PR TITLE
[DROOLS-3119] Implement a Junit activator to be able to run Scenarios via maven

### PR DESCRIPTION
**Pull request by danielezonca**
This PR implement a Junit activator and the mechanism to inject it into user projects be able to run test scenarios via Maven.

**How it works:**
Every time user creates/saves a Test Scenarios asset the service add ScenarioJunitActivatorTest.java as test classes in the default package. It also adds some dependencies to project's POM as test runtime support.

**Dependencies:**
`org.drools:drools-compiler:7.14.0-SNAPSHOT:test`
`org.drools:drools-wb-scenario-simulation-editor-api:7.14.0-SNAPSHOT:test`
`org.drools:drools-wb-scenario-simulation-editor-backend:7.14.0-SNAPSHOT:test`

**How to test:**
- Perform `mvn install` of the project drools-wb/drools-wb-screens/drools-wb-scenario-simulation-editor
- Create a project
- Clone it to verify that no ScenarioJunitActivatorTest class nor POM dependencies added
- Create one or more test scenarios instances
- Refresh local copy
- Perform `mvn test` to run tests

_NOTE: to be able to build locally an user project you need first to change version of plugin kie-maven-plugin to 7.13.0.Final or another non-SNAPSHOT version (it seems there is no SNAPSHOT version of the plugin available on our Nexus)_

@Rikkola @gitgabrio @kkufova

### CODE REVIEW

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
@kkufova 
Fixed

I also added another step to test this PR
_- Perform `mvn install` of the project drools-wb/drools-wb-screens/drools-wb-scenario-simulation-editor_

This is needed because you need to have the new code installed into maven repo/m2 folder

**Comment by danielezonca** [comment]
@kkufova 
Fix another bug
Please not that after junit activator file creation you will find it into asset list too but should not be edited. I have no way to filter it out or similar

**Comment by kkufova** [comment]
@danielezonca, I think I discovered another bug: if you have multiple `.scesim` files with more scenarios, you run the tests using `mvn test` and then you remove one of the files, even the removed tests keep being run (after building the project in Business Central and pulling latest changes).

**Comment by danielezonca** [comment]
@kkufova 

1. Fixed, now the activator is created under the package defined by groupId, i.e. `com.myspace`  
2. I cannot fix it because I need a way to filter out resources from asset list and in general from the WB, please open a Jira for it and approve if there is no other bug :)

**Comment by gitgabrio** [comment]
@danielezonca 
There wqas an empty scesim - I removed it, but the issue somehow still there:

[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 3.209 s <<< FAILURE! - in com.myspace.ScenarioJunitActivatorTest
[ERROR] (org.drools.workbench.screens.scenariosimulation.backend.server.runner.ScenarioRunnerImpl)  Time elapsed: 0.011 s  <<< ERROR!
java.lang.IllegalStateException: Unexpected test error in scenario ''
	at org.drools.workbench.screens.scenariosimulation.backend.server.runner.ScenarioRunnerImpl.internalRunScenario(ScenarioRunnerImpl.java:105)
	at org.drools.workbench.screens.scenariosimulation.backend.server.runner.ScenarioRunnerImpl.run(ScenarioRunnerImpl.java:66)
Caused by: java.lang.NullPointerException
	at org.drools.workbench.screens.scenariosimulation.backend.server.runner.ScenarioRunnerImpl.internalRunScenario(ScenarioRunnerImpl.java:89)
	at org.drools.workbench.screens.scenariosimulation.backend.server.runner.ScenarioRunnerImpl.run(ScenarioRunnerImpl.java:66)

[ERROR] (org.drools.workbench.screens.scenariosimulation.backend.server.runner.ScenarioRunnerImpl)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Unexpected test error in scenario ''
	at org.drools.workbench.screens.scenariosimulation.backend.server.runner.ScenarioRunnerImpl.internalRunScenario(ScenarioRunnerImpl.java:105)
	at org.drools.workbench.screens.scenariosimulation.backend.server.runner.ScenarioRunnerImpl.run(ScenarioRunnerImpl.java:66)
Caused by: java.lang.NullPointerException
	at org.drools.workbench.screens.scenariosimulation.backend.server.runner.ScenarioRunnerImpl.internalRunScenario(ScenarioRunnerImpl.java:89)
	at org.drools.workbench.screens.scenariosimulation.backend.server.runner.ScenarioRunnerImpl.run(ScenarioRunnerImpl.java:66)

[ERROR] (org.drools.workbench.screens.scenariosimulation.backend.server.runner.ScenarioRunnerImpl)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Unexpected test error in scenario ''
	at org.drools.workbench.screens.scenariosimulation.backend.server.runner.ScenarioRunnerImpl.internalRunScenario(ScenarioRunnerImpl.java:105)
	at org.drools.workbench.screens.scenariosimulation.backend.server.runner.ScenarioRunnerImpl.run(ScenarioRunnerImpl.java:66)
Caused by: java.lang.NullPointerException
	at org.drools.workbench.screens.scenariosimulation.backend.server.runner.ScenarioRunnerImpl.internalRunScenario(ScenarioRunnerImpl.java:89)
	at org.drools.workbench.screens.scenariosimulation.backend.server.runner.ScenarioRunnerImpl.run(ScenarioRunnerImpl.java:66)

**Comment by danielezonca** [comment]
@gitgabrio 
Ok I included your bug into this Jira and I will close it later (https://issues.jboss.org/browse/DROOLS-3204), if you have any other comment, can you please approve it?

**Comment by danielezonca** [comment]
@manstis 
Can you please squash and merge?

**Pull request merged**
