### PR TITLE
[DROOLS-3872] 

### PR DESCRIPTION
**Pull request by gitgabrio**
@kkufova @Rikkola @danielezonca…mented test

see https://issues.jboss.org/browse/DROOLS-3872

### CODE REVIEW

**Comment by kkufova** [comment]
One round of testing done. I updated the description of [DROOLS-3872](https://issues.jboss.org/browse/DROOLS-3872).

**Comment by gitgabrio** [comment]
@kkufova 
I've fixed the last bug you mentioned (it was not directly consequent to "rename", but to "set property", so issue was elsewhere)

**Comment by kkufova** [comment]
The second round of testing is finished. I updated the description of [DROOLS-3872](https://issues.jboss.org/browse/DROOLS-3872).

**Comment by gitgabrio** [comment]
@kkufova 
I've made the last fix - pls test again.

**Comment by gitgabrio** [comment]
@manstis
Hi! Could you please merge this, squashing commits? Thanks!

**Pull request merged**
