### PR TITLE
DROOLS-6367: jbpm-bpmn2 dependency is missing from pom.xml

### PR DESCRIPTION
**Pull request by yesamer**
*JIRA**: https://issues.redhat.com/browse/DROOLS-6367

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by yesamer** [comment]
Jenkins retest this

**Review by danielezonca — APPROVED** [review]

**Review by jomarko — COMMENTED** [review]
I can confirm the jbpm dependency is added once scesim file is created.

However I can not confirm the simple project as described in jira (DMN, BPMN, SCESIM) can be started as `mvn clean test`. Please see the jira with attached project `m_m.zip` and error I got.

The error mention this [class](https://github.com/kiegroup/drools/blob/master/kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/ClassLoaderUtil.java), that was touched in the end of March.

As jira reports for 7.10.1 product, I am not sure if just adding jbpm dependency will solve it issue. From my point of view we can:
- resolve the original (adding a jbpm dependency), but create another one
- or we can try to address it as part of this PR.

Please let me know what is your opinion.

**Comment by yesamer** [comment]
> I can confirm the jbpm dependency is added once scesim file is created.
> 
> However I can not confirm the simple project as described in jira (DMN, BPMN, SCESIM) can be started as `mvn clean test`. Please see the jira with attached project `m_m.zip` and error I got.
> 
> The error mention this [class](https://github.com/kiegroup/drools/blob/master/kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/ClassLoaderUtil.java), that was touched in the end of March.
> 
> As jira reports for 7.10.1 product, I am not sure if just adding jbpm dependency will solve it issue. From my point of view we can:
> 
> * resolve the original (adding a jbpm dependency), but create another one
> * or we can try to address it as part of this PR.
> 
> Please let me know what is your opinion.

Thank you for reporting. That's weird, it doesn't reproduce in my local. Which snapshot version of `kie-maven-plugin` did you use?

**Comment by jomarko** [comment]
@yesamer mvn log says `org.kie:kie-maven-plugin:7.55.0-SNAPSHOT:validateDMN`

**Comment by yesamer** [comment]
> @yesamer mvn log says `org.kie:kie-maven-plugin:7.55.0-SNAPSHOT:validateDMN`

Did you compile it in your local machine?  I tried to use 7.54.0 Final version and it works, and 7.55.0-SNAPSHOT (compiled in my local machine and it works as well.

**Comment by jomarko** [comment]
@yesamer in what repo/module I can find kie-maven-plugin please?

**Comment by yesamer** [comment]
> @yesamer in what repo/module I can find kie-maven-plugin please?

@jomarko  https://github.com/kiegroup/droolsjbpm-integration

**Review by jomarko — APPROVED** [review]
https://github.com/kiegroup/drools-wb/pull/1493#issuecomment-847068991 Thank you now it pass.

**Comment by yesamer** [comment]
@danielezonca Can you please merge it?

**Pull request merged**
