### PR TITLE
Drools 3922 Import of external classes in Test Scenario doesn't work until you have a class in your package

### PR DESCRIPTION
**Pull request by gitgabrio**
@kkufova @Rikkola @danielezonca

see https://issues.jboss.org/browse/DROOLS-3922

### CODE REVIEW

**Comment by kkufova** [comment]
@gitgabrio, I haven't discovered any serious bugs. However, could you please explain why it looks like there are two different lists of objects? In my opinion, there should only be one:

bug1

Also, I reported this issue: [DROOLS-3931](https://issues.jboss.org/browse/DROOLS-3931).

**Comment by gitgabrio** [comment]
> @gitgabrio, I haven't discovered any serious bugs. However, could you please explain why it looks like there are two different lists of objects? In my opinion, there should only be one:
> 
> bug1
> 
> Also, I reported this issue: [DROOLS-3931](https://issues.jboss.org/browse/DROOLS-3931).

_This should reflect the types of the items and how they are parsed by the DMN engine. Basically, only *Borrower* is a complex type (so, it is in the upper list) while the others are *simple* types (number/string - so they are below). This is the same as in *Rule* scesim, where you have *bean* types in the upper list (Book, Author, etc.) and simple types below (Boolean, Number, String). Opening the DMN file in the DMN editor seems to confirm that. Please correct me if I'm wrong_

**Comment by kkufova** [comment]
@gitgabrio, in that case, I have a proposal: could we maybe include a headers called for example **Simple Types** and **Complex Types** to make it clear what the division means?

**Comment by gitgabrio** [comment]
@kkufova 
If every one agreed upon, no problem for me. Please keep in mind that beside *Simple Types* and *Complex Types* we also have the *aliases*: just let me know exact wording and css style. @danielezonca WDYT ?

**Comment by kkufova** [comment]
@gitgabrio, you're right! In that case, I would use **Simple Types**, **Complex Types**, and **Custom Instances**. Do you agree? @danielezonca, WDYT?

When it comes to CSS style, I would use the same style as there is for **Select Data Object**.

**Comment by gitgabrio** [comment]
@kkufova 
It is fine for me to do in the current PR - the headers are already in place, I just have to put words in them

**Comment by gitgabrio** [comment]
@kkufova 
Add labels to group separator. Labels should be visible only if the group is not empty. This should work for bot Complex/Simple types and Complex/Simple instances

**Comment by gitgabrio** [comment]
> Please add some unit tests to cover the fixes

_DONE_

**Comment by gitgabrio** [comment]
@manstis
Hi! Could you please merge this, squashing commits? Thanks!

**Pull request merged**
