### PR TITLE
GUVNOR-3091: [Guided Decision Table Graph] DTCellValue value assertion does not work for BigDecimals

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-3091

Discovered whilst looking into a XLS conversion issue on the {{jboss-support-droolsjbpm}} mailing list.

### CODE REVIEW

**Comment by jomarko** [comment]
@manstis sorry I don't manage review today. I will have a look on Monday. Have a nice weekend.

**Comment by manstis** [comment]
@Rikkola I had to fix some of the "Priority Resolver" code for this PR (it appeared to only work due to the bug I fixed here). Could you please review the changes I've made?

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
Jenkins please rebuild this.

**Comment by manstis** [comment]
Jenkins please rebuild this.

**Comment by manstis** [comment]
Jenkins please rebuild this.

**Comment by manstis** [comment]
Jenkins please rebuild this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins execute full downstream build.

**Comment by jomarko** [comment]
screenshot from 2017-05-22 22-21-52
screenshot from 2017-05-22 22-21-13

screenshot from 2017-05-22 22-24-42

**Comment by manstis** [comment]
@jomarko Hello... sorry for not being more clear. The use of "B" in the table itself is covered by https://issues.jboss.org/browse/RHBPMS-4737. During the investigation of which I found, even if I removed the "B" the cell in the resulting GDT was empty. I stepped through the code and found the "value" in the underlying model was a ```BigDecimal``` value "1" but when it was converted to the UI model for the table we were assuming the cell was a ```String```. So, to verify, remove the "B" from your example table and try converting. The cells would be empty before the fix, but contain the value afterwards. Use of "B" will be fixed in the referenced JIRA.

**Pull request merged**
