### PR TITLE
[DROOLS-1608] move processes related classes from drools to jbpm

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by mariofusco** [comment]
depends on kiegroup/drools#1307

**Comment by manstis** [comment]
@mariofusco Is the move still going ahead; or can this be closed?

**Comment by mariofusco** [comment]
@manstis I just summarized the current situation in my comment here https://github.com/kiegroup/jbpm/pull/872#issuecomment-306816403 If this is not a problem please let's keep this PR open and rediscuss it when @mswiderski will be back.

**Comment by manstis** [comment]
@mariofusco @mswiderski Hi.. is this move still going ahead?

**Comment by mswiderski** [comment]
@manstis that's a good question. I was not involved in the origin of this so not sure. @mariofusco what do you think?

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by mariofusco** [comment]
ok to test

**Pull request merged**
