### PR TITLE
JBPM-5876: Fix runtime dependencies

### PR DESCRIPTION
**Pull request by dgutierr**
Add the required dependencies so as to make the project dashboard metrics work in showcase.

@paulovmr I did run it locally without issues. Can you verify please?

### CODE REVIEW

**Comment by dgutierr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
Verified locally, the issue was fixed.

**Comment by Rikkola** [comment]
@dgutierr Thanks

**Comment by manstis** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
The failing is not related: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:209)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:174)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:473)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.get(ClientInvocationBuilder.java:165)
	at org.kie.wb.test.rest.client.RestWorkbenchClient.getJob(RestWorkbenchClient.java:118)
	at org.kie.wb.test.rest.client.RestWorkbenchClient.waitUntilJobFinished(RestWorkbenchClient.java:333)
	at org.kie.wb.test.rest.client.RestWorkbenchClient.waitUntilJobFinished(RestWorkbenchClient.java:323)
	at org.kie.wb.test.rest.client.RestWorkbenchClient.deleteOrganizationalUnit(RestWorkbenchClient.java:251)
	at org.kie.wb.test.rest.RestTestBase.lambda$deleteAllOrganizationalUnits$0(RestTestBase.java:113)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.kie.wb.test.rest.RestTestBase.deleteAllOrganizationalUnits(RestTestBase.java:113)
	at org.kie.wb.test.rest.RestTestBase.cleanUp(RestTestBase.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

**Pull request merged**
