### PR TITLE
BAQE-322 Cover validation of the guided rule with inheritance

### PR DESCRIPTION
**Pull request by jomarko**
This PR cover validation of the guided rule asset while focus on the guided rule that inherit from another guided rule.

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
@manstis tests passed.

**Comment by jomarko** [comment]
@manstis sorry again a question, would you mind if I cherry-pick tests into 7.5.x?

**Comment by manstis** [comment]
@jomarko Fine with me, thanks.

**Pull request merged**
