### PR TITLE
DROOLS-5537 : Performance issue - Test scenario creation for DMN & PMML model

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.redhat.com/browse/DROOLS-5458

### CODE REVIEW

**Comment by jstastny-cz** [comment]
jenkins execute full downstream build

**Comment by jstastny-cz** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
@Rikkola hi, seems one test need a fix `org.drools.workbench.screens.scenariosimulation.backend.server.ScenarioValidationServiceTest.validateSimulationStructure`

**Comment by Rikkola** [comment]
@jomarko Thanks I'll take a look.

**Comment by Rikkola** [comment]
@jomarko Fixed. Had to use the non clone method also in the test.

**Comment by Rikkola** [comment]
@kiegroup/gatekeepers Can I get a merge please.

**Pull request merged**
