### PR TITLE
JBPM-7866 - Remove patternfly css classes

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@gitgabrio see the related issue, I removed the classes/rules that I believe are provided by PatternFly already but please validate if it all works fine for the scenario simulation.

**Comment by gitgabrio** [comment]
@cristianonicolai 
Fine to merge for me, thx!

**Comment by manstis** [comment]
LOL... so GitHub caught up with me approving! (it kept saying it had timed out).

**Comment by manstis** [comment]
@gitgabrio Could you please click the "Approve" button?

**Comment by cristianonicolai** [comment]
thanks guys for definitely approving it :)

**Pull request merged**
