### PR TITLE
GUVNOR-3231: Select placeholder if no operator defined

### PR DESCRIPTION
**Pull request by jomarko**
@manstis @jsoltes please have a look when you have a moment.

### CODE REVIEW

**Comment by jomarko** [comment]
@manstis in my opinion the problems is connected with the `if` you highlighted, however in slightly different way. The given `if` is not executed during first dropdown creation, thus the dropdown seems as first added item (equal to) is selected but the `ValueChangeEvent` was not fired. This PR ensures that "please choose" is selected in the dropdown after first initialization.

**Comment by manstis** [comment]
Thanks for the explanation @jomarko 

Looking at the code in my IDE (as opposed to just the PR) I see ```addPlaceHolder(..)``` is called after the initial operators have been populated and therefore your change seems quite reasonable.

**Comment by manstis** [comment]
@jomarko Failing test ("org.drools.workbench.screens.guided.dtable.client.wizard.column.pages.OperatorPageTest.testOperatorPlaceholderSelectedWhenNothingSelectedPreviously") seems related.

**Comment by jomarko** [comment]
@manstis yes, it is related, I looking right now.

**Comment by jomarko** [comment]
@manstis green now.

**Comment by manstis** [comment]
Thanks @jomarko

**Pull request merged**
