### PR TITLE
RHDM-360: Increase coverage of enum indexing

### PR DESCRIPTION
**Pull request by jomarko**
@manstis please have a look

### CODE REVIEW

**Comment by jomarko** [comment]
@manstis yes agreed, In my eyes, `EnumFileIndexer` is written in so "private" approach, that I can not do much more? Any suggestions welcome.

**Comment by manstis** [comment]
@jomarko Using ```indexer.fillIndexBuilder(..).build()``` will give a ```Set<KProperty<?>>``` that should contain entries for both the Type (```Car```) and Fields (hopefully both ```colour``` and ```price``` however due to RHDM-360 this may not be the case).

**Comment by jomarko** [comment]
@manstis would you mind re-review? I enhanced the test.

**Comment by manstis** [comment]
Thanks @jomarko

**Pull request merged**
